### ISSUE TITLE
Get post, page or category by slug

### ISSUE THREAD

**Issue by Marneus77** [wp-net/WordPressPCL#102]
Which method allows me to get a post, category or page using slug instead of id?
I can't find a way.
e.g. /wp/v2/POSTS?slug=the_slug

**Comment by aaldrich** [comment]
@Marneus77 You can pull a list of posts like this. Not ideal but it works.

client.Posts.GetAll().Result.Where(x => x.Slug.ToLower() == the_slug)

**Comment by Marneus77** [comment]
Ok thanks. I thought maybe with custom query? A GetBySlug would be nice also (like GetById).
It will have to do.

**Comment by ThomasPe** [comment]
We should have this as an option in the query builder. Getting everything from the server first is too expensive.

**Comment by polushinmk** [comment]
For this purpose, it was necessary to create a lot of methods. Such as GetWithInclude, getWithExclude, GetByTags, GetBySearch and so on. We decided that this is not practical and provided you with the opportunity to create a query yourself using QueryBuilder.
For your purposes, the following code is suitable.
```C#
var PostsQuery = new PostsQueryBuilder(){
        Slugs=new string[] { "the_slug1","the_slug2"}
};
var result = await client.Posts.Query(PostsQuery);
```

**Comment by Marneus77** [comment]
Thank you, I'll try this
