### ISSUE TITLE
doesn't have a target for '.NETStandard,Version=v2.0'

### ISSUE THREAD

**Issue by aymangithub** [wp-net/WordPressPCL#103]
please i can't build the project because this error:
Assets file 'C:\Users\My Pc\source\repos\App3\App3\WordPressPCL\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0/win10-x64'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. You may also need to include 'win10-x64' in your project's RuntimeIdentifiers.	WordPressPCL	C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167

**Comment by aymangithub** [comment]
solved after restarting Visual studio !

**Comment by ThomasPe** [comment]
alright then :)
