### ISSUE TITLE
Add to HttpHelper LastResponceHeaders

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#106]
Hi!
I suggest keeping the Headers of the last answer in HttpHelper. This can be useful, for example, to receive such headers from WordPress as X-WP-Total and X-WP-TotalPages. This would help make the normal GetAll method, instead of that where now the library gets 100 entries in an infinite loop until it catches exception :)
What do you think?
https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/

**Comment by ThomasPe** [comment]
you want to keep all headers or just pick the WordPress-relevant ones and store them?
But yes, I like that idea!

**Comment by polushinmk** [comment]
The easiest way is of course to leave all the headers. I do not see scenarios where we will need all headers, except WP headers, but do we need to separate them? For met - translate all headers is easiest way.

**Comment by ThomasPe** [comment]
I'm fine storing all headers, shouldn't make a big difference anyway...
Also, I guess we can keep it for internal usage until someone actually needs it. I probably won't be able to test the PR until tomorrow.
Thanks for your work!
