### ISSUE TITLE
Use WP OAuth Server for authentication

### ISSUE THREAD

**Issue by a-iafrate** [wp-net/WordPressPCL#108]
Please add support for WP OAuth Server for authentication, this is more standard and easy to install on user blog.
Thanks!

**Comment by polushinmk** [comment]
You mentioned this plugin?
https://wordpress.org/plugins/oauth2-provider/

**Comment by a-iafrate** [comment]
Yes!!

**Comment by ThomasPe** [comment]
PRs are always appreciated :D

**Comment by polushinmk** [comment]
I could make a PR and I already has one question/suggestion:
Add method Authenticate and IsAuthenticated instead of current RequestJWToken and IsValidJWToken
it may be looks lake that:
```c#
public async Task Authenticate(AuthMethod method, string username, string password)
{
     switch (method)
     {
           case AuthMethod.JWT:
                   RequestJWToken(login,pass);
                   break;
           case AuthMethod.OAuth:
                   RequestOAuthToken(login,pass);
                   break;
     }
}
```
but it will be breaking change. All users must changed theit code from RequestJWToken(log,pass) to Authenticate(AuthMethod.JWT,login,password).
Or we can leave current JWToken methods and implements new methods for OAuth so it will be:
- RequestJWToken
- IsValidJWToken
- RequestOAuthToken
- IsValidOAuthToken

**Comment by a-iafrate** [comment]
Method can have a default to jwt as last parameter so no change is needed on existed code. Can be a good idea?

**Comment by polushinmk** [comment]
@a-iafrate not really. Now there are only 2 methods: RequestJWToken and IsValidJWToken. And I suggest "hiding" them inside a new, not yet existing, Authenticate method. That is, now all users call RequestJWToken and after they have to change their code to Authenticate

**Comment by a-iafrate** [comment]
@polushinmk yes, i think your solution is the best to make the login agnostic. Another idea is to make these methods deprecated and add the new Authenticate method. what do you think about this?

**Comment by ThomasPe** [comment]
makes sense for me. I don't mind the breaking changes since they are not that though to overcome.

**Comment by polushinmk** [comment]
@ThomasPe I will clarify to make sure that I understand you correctly:
We choose the option to create a new common Authenticate method, and we hide / mark the current RequestJWToken and IsJWTokenValid methods as obsolete.
All right?

**Comment by ThomasPe** [comment]
Sounds good!

**Comment by polushinmk** [comment]
@ThomasPe @a-iafrate To use this plug-in in our library, we need to enable **client credentials** or **user credentials** from the grant types section. But these types are only available in the **Pro** version of the plugin. Are we sure that we want to use it?
https://wp-oauth.com/documentation/grant-types/

**Comment by ThomasPe** [comment]
Over a hundred dollars is quite pricy.
This plugin is being linked to from the official docs, not sure if it works though.
https://wordpress.org/plugins/rest-api-oauth1/

**Comment by polushinmk** [comment]
This plugin works, but supports only OAuth1.0a (currently stable OAuth2.0) and it also does not suit us.
The authorization and authentication process takes place in 3 stages (https://github.com/WP-API/OAuth1/blob/master/docs/basics/Auth-Flow.md):
1) Temporary Credentials Acquisition
2) Authorization
3) Token Exchange

Steps 1 and 3 can be implemented in our library, but step 2 requires user participation. It should open in the browser page http://sitedomain.com/oauth1/authorize?oauth_token=TOKEN_FROM_1_STEP -> will be redirected to the wordpress authorization page where it will enter its login and password and after that the authorization code will be returned to it. Our library can not provide user interaction with the browser.

In the version of oauth2.0, two more authorization methods were added:
- Resource Owner Password Credentials
- Client Credentials

But both are available in the plug-in https://wordpress.org/plugins/oauth2-provider/ only in the PRO version.

P.S. small remark: if library users independently receive token from oauth server, then they can use it in the library by passing it via the SetJWToken method. The IsJWTokenValid method certainly will not work, but Bearer Token will be added to the Header and in this case the requests with authorization should work.

**Comment by ThomasPe** [comment]
I see, thanks for the clarification!
@a-iafrate is this still something you're looking for even when the paid version is required?

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!
