### ISSUE TITLE
Post.query with "statuses" filter does not work

### ISSUE THREAD

**Issue by Marneus77** [wp-net/WordPressPCL#109]
When making a postquery with filter on status, an error comes: "invalid parameter: status"
Querytext should be "statuses"

       /// <summary>
        /// Limit result set to posts assigned one or more statuses.
        /// </summary>
        /// <remarks>Default: publish</remarks>
        [QueryText("statuses")]
        public Status[] Statuses { get; set; }

It's probably the same in others utility.querybuilder classes.

More than that, once fixed, I seem to be still only getting the default "publish". This problem seems to be coming from Wordpress.com because entering the url manually with &statuses=draft,pending returns published posts too

**Comment by ThomasPe** [comment]
so this is a wordpress.com issue, not with self-hosted wordpress sites?
[The WordPress Rest API Docs](https://developer.wordpress.org/rest-api/reference/posts/) have it as `status`.

**Comment by polushinmk** [comment]
@Marneus77 to query posts by statuses you must use authorization. So try to change your code like:
```c#
var result = await client.Posts.Query(postsquerybuilder,true);
```

**Comment by Marneus77** [comment]
I checked a self-hosted WP site, it's the same: statuses 

Thanks for the tip. But I then have to implement authentication? I don't have the jwt plugin installed on the blog, how do I authenticate?

**Comment by polushinmk** [comment]
Install JWT and configure it.
Field name is **status**. You could check it in wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php line 184
**Statuses** isn`t exist in WP REST API so it ignores it and returns default - publish posts.
