### ISSUE TITLE
return role of user

### ISSUE THREAD

**Issue by umarsolehri** [wp-net/WordPressPCL#110]
user role returns null while getting user or users , so check that issue Or add that feature which return role  of user while fetching users list or single user

**Comment by polushinmk** [comment]
Hi! this fields abailable only in edit context.
Now you can get this only through QueryBuilder specifying Context = edit
Example:
```C#
var usersquery = new UsersSqueryBuilder()
{
    Context=Context.Edit
};
var users = client.Users.Query(usersquery);
```

@ThomasPe should we add a context property to all of our endpoints like this done now with embeds?

**Comment by ThomasPe** [comment]
mh, I don't think that this is necessary for now since the context will probably be used far less often than _embed.
Also, _embed is a global parameter according to the WordPress REST API Handbook, context is not.

**Comment by ThomasPe** [comment]
@umarsolehri did this work for you as proposed by @polushinmk?

**Comment by umarsolehri** [comment]
why we have to query when we can get all fields by simple query. this api is totally senseless

**Comment by ThomasPe** [comment]
k, thx.
