### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by davewolfe** [wp-net/WordPressPCL#111]
Using https://blahblahblah.com/wp-json/jwt-auth/v1/token/ as my endpoint, and I get a route not found error.  I have only the WP-REST-API and JWT Auth plugins installed and activated.

**Comment by polushinmk** [comment]
Hi!
Do you use the path https://blahblahblah.com/wp-json/jwt-auth/v1/token/ as the path to your site? like that?
```c#
var client = new WordpressClient("https://blahblahblah.com/wp-json/jwt-auth/v1/token/");
```
You should use the link in the following format: https://blahblahblah.com/wp-json/ without jwt-auth/v1/token

It is also necessary to configure the jwt-auth plugin as specified here
https://ru.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by davewolfe** [comment]
That was it. Using only wp-json works.

**Comment by ThomasPe** [comment]
thanks @polushinmk
