### ISSUE TITLE
Delete requests do not work when WordPressPCL NuGet package is used in .NET Framework project

### ISSUE THREAD

**Issue by zielo-it** [wp-net/WordPressPCL#113]
Problem exists when execution is dealing with `HttpResponseMessage` type. My project uses .NET Framework 4.6.1. When I copied WordpressPCL project into my solution and changed `HttpHelper.DeleteRequest` method to return `Task<bool>` instead of `Task<HttpResponseMessage>` code began to work. Otherwise I get following `MissingMethodException`:

`'System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task'1<System.Net.Http.HttpResponseMessage> WordPressPCL.Client.CustomRequest.Delete(System.String)'.`

I've used WordPressPCL v1.4.0

**Comment by ThomasPe** [comment]
can you share a repo of this?

**Comment by zielo-it** [comment]
https://github.com/zielo-it/wordpress-pcl-usecase

**Comment by polushinmk** [comment]
Hi @zielo-it !
I foud a fix. It seems, that it is problem in System.Net.Http module.
You should change in app.config
from:
```
<dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.3" newVersion="4.3.3" />
      </dependentAssembly>
```
to
```
<dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>
```
It works for me.

@ThomasPe what do you think about changing return value of Delete function from **HttpResponseMessage** to **bool**?

**Comment by ThomasPe** [comment]
Huh, interesting. 
I'm ok with changing this to bool since it will throw an exception if anything goes wrong anyway, right?

**Comment by polushinmk** [comment]
I see 2 options:
1) throw an exception, when Delete request cannot be execute
2) return not only bool, but bool+string. string - info message. If bool true - info null, if bool false - info contains responce from WP

but it is another BC :( All users must changed there delete method usages

**Comment by ThomasPe** [comment]
I think I would prefer the first one - do you have a preference?

**Comment by zielo-it** [comment]
First option works for me :+1:

**Comment by ThomasPe** [comment]
I've just updated the NuGet package, should be available in the next hour or so.

**Comment by polushinmk** [comment]
@ThomasPe but you didn`t merge this pr #114 . Are you missed it?

**Comment by ThomasPe** [comment]
oh no, I did o.O
give me a sec
