### ISSUE TITLE
GetAll for Media items fails when WP decides to omit a page item

### ISSUE THREAD

**Issue by drhoroscope** [wp-net/WordPressPCL#115]
We've seen a WordPress behavior where WP passes back 99 media items when a page of 100 is requested. This stops the media type iteration prematurely.

**Comment by drhoroscope** [comment]
OK, sorry I see that this issue has been fixed in [this commit](https://github.com/wp-net/WordPressPCL/commit/12af639bf06b4f5b1e2a27c2c7459d3a029d7329). Sorry I was working with out-of-date source

**Comment by ThomasPe** [comment]
A new release should be available through NuGet shortly.

**Comment by drhoroscope** [comment]
I can't thank you enough for getting this out! Updated to 1.4.2 and all tests are green.

**Comment by ThomasPe** [comment]
Glad to hear!
