### ISSUE TITLE
Use this NuGET on Xamarin.Android to authenticate and then Load URL on a WebView

### ISSUE THREAD

**Issue by CDrosos** [wp-net/WordPressPCL#116]
im wondering if is possible somehow to do something like this:
use this package to authenticate on a wordpress site and then load a private post from url with WebView.LoadURL on Xamarin.Android. (i don't want to get the data content from a post, i want to load a url from a password protected website that requires login first)
Can somehow create a cookie with this package and use it on the webview?

**Comment by ThomasPe** [comment]
The only thing I can say for sure is that this does not work currently with this package ;-)
We currently do not support Cookie-Authentication and reading the [REST API Handbook](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/) I'm not sure if that would be even possible.

If this could be done by handling the required headers I would be open to adding this, though. Do you have any experience with this?

**Comment by CDrosos** [comment]
if this is not supported by this package then the next solution that is coming to my mind is to add custom headers on the webview and check on the website if the headers are available and only then load my content. 

I'm not sure i understand what you mean by "handling the required headers manually". how can this be done by this package? you mean to just create some headers with this package and then pass those headers in the WebView?

**Comment by ThomasPe** [comment]
sounds like the thing you're trying to do is not really something this library can help you with.
unfortunately there seems to be no built-in authentication endpoint that would return a cookie so you might need to do this another way.
Maybe you could create a page template that checks for an authorization code in the URL and only then returns the content - just a thought.
