### ISSUE TITLE
Pages Tags is not available in Post method.

### ISSUE THREAD

**Issue by Supermakaka** [wp-net/WordPressPCL#117]
Hi all!
https://www.screencast.com/t/Wt6yliNYk -> In WP Pages we have tags, but in the Page model we don't have them (https://www.screencast.com/t/zClMGAbwJvw) like in Post model (https://www.screencast.com/t/MSgQGFvW). Can I access Pages Tags any other way? 

Thanks!

**Comment by ThomasPe** [comment]
you can create custom requests with [your own models like this](https://github.com/wp-net/WordPressPCL/wiki/CustomRequests). First thing you should to though is make sure your API actually returns those tags with your posts. Then you could create your own model base on our Page model.

**Comment by Supermakaka** [comment]
Thanks! Looks like they don't include tags in page response object.  ((( https://www.screencast.com/t/GcWAfqyF3N

**Comment by ThomasPe** [comment]
Tags are not enabled for Pages in WordPress by default, so you will have to [enable them for the API manually in your functions.php](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/).
