### ISSUE TITLE
Media.GetAll() JsonReaderException

### ISSUE THREAD

**Issue by jmead** [wp-net/WordPressPCL#118]
Hi Guys,

We are getting JsonReaderException: Unexpected character encountered while parsing value: <. Path ", line 0, position 0. 

I believe the issue is with the html found in:
`
"description": {
                "rendered": "<p class="attachment"><a href='https://www.pcsupacentre.com.au/wp-content/uploads/2017/09/c05473521-8.jpg'><img width="500" height="374" src="https://www.pcsupacentre.com.au/wp-content/uploads/2017/09/c05473521-8-500x374.jpg" class="attachment-medium size-medium" alt="" /></a></p>
"
`
Example: https://www.pcsupacentre.com.au/wp-json/wp/v2/media

I have found the notes on the feature in Wordpress
https://core.trac.wordpress.org/ticket/39185

**Comment by ThomasPe** [comment]
Interesting, I'll update the tests with some description content to see whether I can get it to break. ;-)

**Comment by ThomasPe** [comment]
I just used the Media.GET method on your endpoint and it deserialized fine for me. In what kind of application are you using the library?

**Comment by jmead** [comment]
All sorted. I’ll share my code when I get into the office. I’m making a ConsoleApp to parse large amounts of XML files.



		Regards,Jason  Mead - Director | +612 8922 9800Trucell | L1 448 Church Street Ph  +612 8922 9800 | www.trucell.com.au

**Comment by jmead** [comment]
I personally think the following method is the best method for processing media.getall()

`
WordPressClient wpc = GetAuthenticatedWordPressClient();

            

            List<MediaItem> mediaItems = new List<MediaItem>();

            bool endWhile = false;
            int totalMedia = 0;

            var queryBuilder = new MediaQueryBuilder();
            queryBuilder.PerPage = 40;
            queryBuilder.Page = 1;
            queryBuilder.Context = Context.View;
            queryBuilder.MediaType = MediaQueryType.Image;

            while (!endWhile)
            {
                try
                {
                    // returns result of query
                    Console.WriteLine("Fetching Media - Page: " + queryBuilder.Page);
                    var mediaTemp = wpc.Media.Query(queryBuilder);
                    
                    if (mediaTemp.Result.Count() > 1)
                    {
                        Console.WriteLine("Found Media - Count: " + mediaTemp.Result.Count());
                        mediaItems.AddRange(mediaTemp.Result.ToList());

                        Console.WriteLine("Incrementing to next media page: " + queryBuilder.Page);
                        queryBuilder.Page++;

                        Console.WriteLine("Processed: " + totalMedia);
                        totalMedia = totalMedia + mediaTemp.Result.Count();
                    }
                    else
                    {
                        endWhile = true;
                    }
                }
                catch
                {

                }
            }
`
