### ISSUE TITLE
Edit Post

### ISSUE THREAD

**Issue by geniovi** [wp-net/WordPressPCL#12]
hello, it is possibile EDIT exists post?

var client = new WordPressClient("mysite.com/wp-json");
client.Username = "user";
client.Password = "password";
var postbyid = await client.GetPost(id);
postbyid.Content.Raw = "Edit content";

And Save?

Thanks

**Comment by ThomasPe** [comment]
Hey
The core should be ready to support saving edited posts. However there's no public method nor tests for that yet. But that's certainly something this library should support.

I'll have a closer look tonight at what's necessary to achieve this (the WordPress API is a bit weird with creating / updating posts).

**Comment by geniovi** [comment]
Ok thanks 
i'm waiting

**Comment by ThomasPe** [comment]
I've added a UpdatePost method to the client. I haven't published this to the nuget feed yet since I had no time testing it fully.
Maybe you could test the code to see if it works for you as you expect it to.
