### ISSUE TITLE
Best way to change post

### ISSUE THREAD

**Issue by Diddlik** [wp-net/WordPressPCL#120]
Hello, what is the best way to change something in a post and update it. 
```
             var pp = sp.Posts.FirstOrDefault(ps => ps.Id == 592);
                  //check if changes need
                  if (isNeedToFix(p.Content.Rendered))   
                   {
                         //p.Content.Raw = FixedContent(p.Content.Rendered);
                        p.Content = new Content(FixedContent(p.Content.Rendered));
                        //Push changes back
                        if (await clientRest.IsValidJWToken())
                        {
                            var updatedPost = await clientRest.Posts.Update(p);
                        }
                    }
```
What does Content.Raw and Content.Rendered mean? 
Why ist Content.Raw is null after I got Post from WP?

Sincerely,
Pavel

**Comment by polushinmk** [comment]
Hi!
_Raw_ field available only in context=edit request. By default all requests performs with context=view.
I didn`t find any info about what difference between _raw_ and _rendered_ content  in official docs :(
For the most common scenarious to update the post content you should do it like this
```c#
p.Content = new Content("content");
```
