### ISSUE TITLE
Get Media in "draft" status

### ISSUE THREAD

**Issue by frenchdonah** [wp-net/WordPressPCL#121]
Hi, 

I need to build a query with MediaQuery obtaining a list of media with status "draft", but in enum WordPressPCL.Models.MediaQueryStatus we have only three states: Inherit, Private and Trash. 

"Inherit" include also draft status? If not, it is possibile to add statuses that are missing? (statuses available: publish, future, draft, pending, private)
https://developer.wordpress.org/rest-api/reference/media/#schema

Thanks

**Comment by ThomasPe** [comment]
Guess you are right, we would need to add the missing statuses to the MediaQueryStatus enum - care to submit a PR?

**Comment by polushinmk** [comment]
It seems that _publish, future, draft, pending, private_ statuses available for media create but not for media query. For media query availables only 3 statuses: _inherit, private, trash_
https://developer.wordpress.org/rest-api/reference/media/#arguments
or you can see it in rest api source code
https://github.com/WordPress/WordPress/blob/54f004e18440f1cbbca860d514c5e21443be517d/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L656

**Comment by frenchdonah** [comment]
From in this link ("List Media"):
https://developer.wordpress.org/rest-api/reference/media/#arguments
is written:

"status" -> Limit result set to posts assigned one or more statuses.
Default: inherit

when I read "one or more statuses" I expect to find statuses in "Schema"
https://developer.wordpress.org/rest-api/reference/media/#schema
and in schema all statuses are presents (publish, future, draft, pending, private)

But in wordpress code is clear that there are only three statuses available ('inherit', 'private', 'trash') that are also in WordPressPCL so my question is: there is a way to get media in "draft" status (attached to a post that is not published)

thanks

**Comment by polushinmk** [comment]
You can perform it with 2 steps:
1) Get posts with status=draft
ex.:
```c#
var draftPosts = await client.Posts.Query(new PostsQueryBuilder(){
                   Statuses=new Status[]{ Status.Draft }},true);
//get an array of posts IDs
var draftPostsIDs = draftPosts.Select (a=>a.ID).ToArray();
```
2) for each draft post retrive its media
```c#
var mediaForDraftPosts = await client.Media.Query(new MediaQueryBuilder(){
                                         Parents=draftPostsIDs },true);
```

Notes:
1. This is an example code, I didn`t test it, so it may contains errors
2. All operations with draft objects must be executed with authentication headers
