### ISSUE TITLE
Sorry, you are not allowed to create new terms.

### ISSUE THREAD

**Issue by ajaybommena** [wp-net/WordPressPCL#124]
I am able to successfully get the token for the credentials provided. However while doing create, update or delete operation I am getting exceptions like if we are tying to create we get Sorry, you are not allowed to create new terms.

I have installed JWT Authentication for WP REST API
Using WP Version 4.9.6
Trying in localhost

**Comment by ThomasPe** [comment]
Can you post the code how you're trying to update a post?

**Comment by ajaybommena** [comment]
I am just running the unit tests provided.
Just want to update you that I have deployed my WP in localhost. 
I have also done PHP HTTP AUTHORIZATION HEADER ENABLE from .htaccess file and add JWT_AUTH_SECRET_KEY in wp-config.php

**Comment by ThomasPe** [comment]
Did you enter the credentials of an admin user in the ApiCredentials.cs?

**Comment by ajaybommena** [comment]
Issue got resolved. Seems like JWT_AUTH_SECRET_KEY in wp-config.php should be same as admin password which I have missed.

**Comment by ThomasPe** [comment]
That doesn't seem right? You should never add your admin password to any of the php files...

**Comment by ajaybommena** [comment]
Yes you are so true. I missed this important point. I have changed by used a string from here https://api.wordpress.org/secret-key/1.1/salt/.
and Its working now. 

Thanks A lot 👍
