### ISSUE TITLE
Authorization header not found

### ISSUE THREAD

**Issue by ZhaoXiangXML** [wp-net/WordPressPCL#128]
I'm having this error message: `{"code":"jwt_auth_no_auth_header","message":"Authorization header not found.","data":{"status":403}}` when calling `await client.IsValidJWToken()`.

It looks like I did not config my `.htaccess` correctly. The content of this file is like this:

```# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /wordpress/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</IfModule>

# END WordPress
```

This file is in my `/var/www/html/wordpress/` folder.

I'm very new to this stuff, I'm not sure if I'm doing this right, is there something wrong here or it could be some other problem?

Thanks

**Comment by ZhaoXiangXML** [comment]
I've tried to move the line `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` before or after everything else, still no lucky

**Comment by TylerByte666** [comment]
@ZhaoXiangXML  Have you tried moving SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1 out of the <IfModule></IfModule> then restart webserver?

**Comment by ZhaoXiangXML** [comment]
@TylerByte666 thanks, it works after I restarted Apache. Thank you.
