### ISSUE TITLE
Post Raw Content always returns null 

### ISSUE THREAD

**Issue by optionsgithubuser** [wp-net/WordPressPCL#129]
I am trying to get all posts from my wordpress site. and that code is working fine and it can grab the posts. 

However, the problem is I cannot get the raw content from the posts. It is rendering it as HTML. I am using markdown in my posts and want to get that information.The raw content always returns null. Any idea on why this is happening? 

![image](https://user-images.githubusercontent.com/26908644/43408444-6545bb72-93ef-11e8-9fce-2c79d70878cb.png)

 return await client.Posts.GetAll(false, true);

Let me know if I am doing something wrong. 

Thanks for the plugin!

**Comment by ThomasPe** [comment]
Afaik raw content will only be included when the call is authorized and in edit mode. So you'll probably need to build  a custom query.

**Comment by optionsgithubuser** [comment]
Thanks for the reply. I am authorizing the call on admin credentials. 

To get to edit mode, I have to build a custom query then? Is there any documentation on that?

**Comment by optionsgithubuser** [comment]
Thank you very much for the information! it is very helpful because I was able to get the basic raw information and not the rendered one. However, I am thinking that Wordpress actually doesn't store it as markdown and just converts it for you when you are editing.

I am using Html2Markdown and it seems to be converting most of them fine. 

Thank you again for your help!
