### ISSUE TITLE
how to bind featuredImage to xmal imagesource 

### ISSUE THREAD

**Issue by mickeymarko** [wp-net/WordPressPCL#130]
hi, can someone let me know how can I bing post featuredimag to imagesource on Xaml

**Comment by tscholze** [comment]
@mickeymarko Could you please explain what do you actual mean? 
Do the `SourceUrl` from a image-typed filtered `Post.Embedded.WpFeaturedmedia` enumeration not work if you wanna use them in the `Source` property of an `Image` XAML control? 

If the list is empty, you could check if the Wordpress installation is configured to set this value. Often you have to use the first image of the content instead.

**Comment by mickeymarko** [comment]
hi, yes this exactly what I'm looking for. 
can you advice how to enable the Embedded on Wordpres setting?

**Comment by ThomasPe** [comment]
Have you

**Comment by ThomasPe** [comment]
Have you set the embed boolean when getting the posts?

**Comment by mickeymarko** [comment]
thanks that what I missed
