### ISSUE TITLE
post get all embedded 

### ISSUE THREAD

**Issue by mickeymarko** [wp-net/WordPressPCL#131]
when assigning true to get all post method it's return null 
_posts = new ObservableCollection<Post>(await _client.Posts.GetAll(true));

please advise.

**Comment by ThomasPe** [comment]
have you tried to do this in two separate steps?
```
var p = await _client.Posts.GetAll(true);
_posts = new ObservableCollection(p);
```
Try it this way to make sure `p` is not `null`.
