### ISSUE TITLE
Question: is there any way set post resolution

### ISSUE THREAD

**Issue by mickeymarko** [wp-net/WordPressPCL#132]
I'm using Xamarin Webview to display the rendered content of a post and wondering if the any way to get the post rendered to mobile

**Comment by ThomasPe** [comment]
You mean like adding Css to make the Content responsive?
I've done this in der WordPressUWP project if you want to take a look.

**Comment by mickeymarko** [comment]
Hi Thomas, this is exactly what I'm looking for. 
Can you please send me link to project

**Comment by ThomasPe** [comment]
https://github.com/wp-net/WordPressUWP/tree/master/WordPressUWP/Assets/Web

**Comment by ThomasPe** [comment]
Thats just an example how I did this in UWP. You should be able to modify your HTML similarly (look at the HTML Helper class).

**Comment by mickeymarko** [comment]
Thanks
