### ISSUE TITLE
Create comment return error

### ISSUE THREAD

**Issue by mickeymarko** [wp-net/WordPressPCL#133]
I'm using a registered user authorization level subscription 
when trying to create a new comment get erorr that this user cannot edit comment status. 

Comment c = new Comment();
            c.Content = new Content("בדיקה אפליקציה");
            c.PostId = _post.Id;
            c.AuthorEmail = "myemail";
            c.AuthorId = myid;
            c.Status = CommentStatus.Pending; 
           

            try
            {
                var createdComment = await SiteConnectionService._client.Comments.Create(c);
            }
            catch (Exception ex)
            {

            }

**Comment by mickeymarko** [comment]
thanks for replaying is there any way to leave a comment when the user is not admin? 
I want to enable comment leaving from all users using the API

**Comment by ThomasPe** [comment]
Just don't set the status at all

**Comment by mickeymarko** [comment]
Even if no status is set same error returned

**Comment by mickeymarko** [comment]
any solution to this issue?

**Comment by ThomasPe** [comment]
can you show the code how you authorize your user?
also, here's a link to the Wiki in case you have not seen it: 
https://github.com/wp-net/WordPressPCL/wiki/Working-with-Comments#create-new-comment

**Comment by mickeymarko** [comment]
here is the authorization code: 
` await SiteConnectionService._client.RequestJWToken(RegisteredUser.Email, RegisteredUser.Password);`
and tring to create comment:
` private async void NewCommentButton_Clicked(object sender, EventArgs e)
        {
            Comment c = new Comment();
            c.Content = new Content("בדיקה אפליקציה");
            c.PostId = _post.Id;
            c.AuthorEmail = "mickey@blogever.co.il";
            c.AuthorId = 569;
            c.Status = CommentStatus.Pending;


            try
            {
                if (await SiteConnectionService._client.IsValidJWToken())
                {
                    var createdComment = await SiteConnectionService._client.Comments.Create(c); 
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("can't save comment" + ex.Message);
            }
        }`

**Comment by mickeymarko** [comment]
also tested:
` private async void NewCommentButton_Clicked(object sender, EventArgs e)
        {
            Comment c = new Comment();
            c.Content = new Content("בדיקה אפליקציה");
            c.PostId = _post.Id;
            c.AuthorEmail = "mickey@blogever.co.il";
            c.AuthorId = 569;



            try
            {
                if (await SiteConnectionService._client.IsValidJWToken())
                {
                    var createdComment = await SiteConnectionService._client.Comments.Create(c); 
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("can't save comment" + ex.Message);
            }
        }`

**Comment by polushinmk** [comment]
@ThomasPe pls see #134

**Comment by ThomasPe** [comment]
the update has been pushed to nuget and should be available shortly.
