### ISSUE TITLE
Please consider using this plugin for Authentication

### ISSUE THREAD

**Issue by chrisgate** [wp-net/WordPressPCL#135]
Nice Library we had here.
Can you please consider this plugin for authentication:
https://github.com/jonathan-dejong/simple-jwt-authentication

by @jonathan-dejong

The plugin is same as the one we have here but re-written with active maintenance .

Thanks

**Comment by ThomasPe** [comment]
I'm certainly open to supporting different authentication plugins. I guess we should have an enum for all supported plugins to configure the client.

I'm not sure when I'll be able to add this, but I'm always open to check PRs. :)

**Comment by chrisgate** [comment]
Can u point me to where the enum is appropriate.

for the above plugin i just changed         
private const string _jwtPath = "jwt-auth/v1/";
to
private const string _jwtPath = "simple-jwt-authentication/v1/";
 
Viola everything is cool

But i am not using nuget but referencing the library directly on my Xamarin Forms bcoz of the above changes.

**Comment by ThomasPe** [comment]
There's no enum - yet. Cool that it's so easy :)

**Comment by chrisgate** [comment]
the plugin is cooler and the the guy is responsive just like you.....please consider.

Thanks

**Comment by ThomasPe** [comment]
plugin is no longer maintained
