### ISSUE TITLE
Unable to get username from user

### ISSUE THREAD

**Issue by MarvinKlar** [wp-net/WordPressPCL#137]
Hello everyone,

I was unable to get the users usernames with your api. I am using the function `GetAll(True, True)` to get all users. But the username is not set in the returned `User` objects.
In the documentation https://developer.wordpress.org/rest-api/reference/users/#arguments there is a `context` argument, which can be either `view`, `embed` or `edit`. I noticed, that most of the users attributes are available in the `edit` context. But you can only specify to use the `embed` context or not with your api. Is that the reason why I am no receiving the usernames of the users?

Thank you very much for your help!

**Comment by chrisgate** [comment]
Hope u set ur .htaccess

**Comment by MarvinKlar** [comment]
I did.

**Comment by chrisgate** [comment]
Check again..........maybe it reset back

**Comment by MarvinKlar** [comment]
[htaccess.txt](https://github.com/wp-net/WordPressPCL/files/2345206/htaccess.txt)

Is there anything wrong?

**Comment by chrisgate** [comment]
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
# END WordPress

**Comment by chrisgate** [comment]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

This part should be outside

**Comment by MarvinKlar** [comment]
The api request result is the same.

**Comment by ThomasPe** [comment]
If you need a field that's not available in the view context you need to create a custom query using the [QueryBuilder](https://github.com/wp-net/WordPressPCL/wiki/Working-with-Users#query). The GetAll-method only works for the `view` context.

**Comment by MarvinKlar** [comment]
`You need to be authenticated to get data in the edit context.` - But I authenticated myself with your api?!

Would be great if you provide this feature! So you don't have to do this manually....

**Comment by ThomasPe** [comment]
With my api? What api?
WordPressPCL does support authentication using this [JWT Authentication plugin](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/#description).
https://github.com/wp-net/WordPressPCL/wiki#basic-usage

**Comment by chrisgate** [comment]
my bad ...........if u can validate ur token then ur .htaccess is good.

**Comment by MarvinKlar** [comment]
I meant the client, which consumes the api. It doesN#t matter if you use the default authentication or the JWT auth. Both doen't return the usernames!

The features would be nice anyway...

**Comment by chrisgate** [comment]
/// <summary>
        /// Get current User
        /// </summary>
        /// <returns>Current User</returns>
        public Task<User> GetCurrentUser()
        {
            return _httpHelper.GetRequest<User>($"{_defaultPath}{_methodPath}/me", true, true);
        }

 
I think this is what /me can give you.


so my question @ThomasPe is there no other ways to get current user?

**Comment by polushinmk** [comment]
@MarvinKlar if you want to perform the request with special context (not view), you should use QueryBuilder. For your purpose the following code might be helpful:
```c#
var userQuery = new UsersQueryBuilder {
     Context=Context.Edit,
//another conditions
};
var usersWithUsername = client.Users.Query(userQuery, true);
```
so this code should return users with username property
