### ISSUE TITLE
Losing information in unexpected error scenarios

### ISSUE THREAD

**Issue by drhoroscope** [wp-net/WordPressPCL#138]
In HttpHelper.cs we find this bit:
```
                if (response.IsSuccessStatusCode)
                {
                    // ...
                }
                else
                {
                    Debug.WriteLine(responseString);
                    var badrequest = JsonConvert.DeserializeObject<BadRequest>(responseString);
                    throw new WPException(badrequest.Message, badrequest);
                }
```
This works fine when you're querying a valid WordPress API well enough so you get a well formed bad request response. But in a wide range of error scenarios the call to DeserializeObject() blows up and throws an exception up the stack without logging some critical information, such as the HTTP response code and the URL being referenced. The Debug statement is arguably some help, but in most configurations that trace isn't going to hit a log file, which means if you've debugging a server issue you're staring at a now familiar error:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0
```
with no actionable information about what the underlying problem is. My suggestion is that we use an error handling delegate to catch the deserialization error and, in the event of a deserialization error, we record context information, including the HTTP status code, request URL, and possibly other details in some standard format, either using the existing BadRequest structure or possibly a new data format created for this purpose.

I'd be happy to submit a PR for this, but just wanted to get some review and guidance first.

**Comment by ThomasPe** [comment]
I agree that error handling should be definitely improved and I'm certainly open to suggestions / PRs!
@polushinmk any thoughts on this?

**Comment by polushinmk** [comment]
@ThomasPe  @drhoroscope Yeah, I agree too that this is good suggestion. For now we really loosing info about non wordpress-specific bad requests. What about realisation? I see these approaches:

- If Json deserialization to WPBadRequest fails - throw an exception with HTTP request&responce info
- add a delegate (like HttpPrePocessing) which can be used for log all requests and responces info

and, I think, we could combine them together.

**Comment by drhoroscope** [comment]
@polushinmk sounds good - I will work on a PR for this

**Comment by ThomasPe** [comment]
Package has been updated on nuget.org.
