### ISSUE TITLE
Tests.Selfhosted on Visual Studio 2017 Community macOS: The name 'ApiCredentials' does not exist in the current context (CS0103)

### ISSUE THREAD

**Issue by ruffin--** [wp-net/WordPressPCL#140]
I'm trying to run the self hosted tests on Visual Studio 2017 Community on macOS. After changing the `Project Options >>> Build >>> General >>> Target Framework` from `.NET Standard 1.0` to `.NET Standard 2.0`, which Tests.Selfhosted expected, I'm getting errors everywhere `ApiCredentials` is used.

Example:
`/Users/myLogin/Projects/WordPressPCL/WordPressPCL.Tests.Selfhosted/Utility/HttpHelper_Tests.cs(46,46): Error CS0103: The name 'ApiCredentials' does not exist in the current context (CS0103) (WordPressPCL.Tests.Selfhosted)`

I have run `dotnet restore` on each project's root dir.

Sure enough, when I search the entire solution, there's no file defining the ApiCredentials class. I've also noticed that the [`.gitignore` file explicitly ignores a few examples of the file](https://github.com/wp-net/WordPressPCL/blob/5ce0f630f3a4811d3134a3d0992254724f6d5f16/.gitignore#L249), though they all appear to be in testing folders, even though ApiCredentials is clearly included inthe [WordpresPCL quickstart instructions](https://github.com/wp-net/WordPressPCL#quickstart-using-the-api-wrapper). 

Strangely, however, there's no mention of a constructor with `ApiCredentials` in it in [`WordPressClient`](https://github.com/wp-net/WordPressPCL/blob/master/WordPressPCL/WordPressClient.cs). I'm pretty sure this isn't part of a Microsoft library I'm missing, as a search for `C# apicredentials` turns up [mostly 3rd party stuff](https://www.google.com/search?q=c%23+%22apicredentials%22&oq=c%23+%22apicredentials%22&)

I did not find any ApiCredential issues when I searched in open or [closed](https://github.com/wp-net/WordPressPCL/issues?q=is%3Aissue+apicredentials+is%3Aclosed) issues.

Apologies for overlooking something, but I'm not sure what I've missed.

**Comment by ThomasPe** [comment]
We have indeed excluded the `ApiCredentials` class in the gitignore to prevent people (mostly me) accidentally checking in their WordPress admin passwords.
There's a `ApiCredentials-sample.cs` file inside the Utility folder which you can copy & rename.

You're right though, we should add some "getting started with development" guidelines to the readme explaining this.
