### ISSUE TITLE
Spelling corrections on GitHub

### ISSUE THREAD

**Issue by RecursiveGeek** [wp-net/WordPressPCL#146]
I thought you might like to know...

On the https://github.com/wp-net/WordPressPCL page, the introduction (which is shown prominently on Google search results) line there is a typo:

This is a portable library for **consuimg** the WordPress REST-API in (almost) any C# application.  The word 'consuimg' should be change to 'consuming' (right letters, just a reordering :-))

In the Contributions Guidelines section there are 2 items:

First, create an issue describing what feature you want to add **of** what problem you're trying to solve, just to make sure no one is already working on that. That also gives us a chance to debate whether a feature is **wihtin** the scope of this project.

I think 'of' should be changed to 'or' and 'wihtin' should be changed to 'within'.

**Comment by ThomasPe** [comment]
I've fixed the latter two typos, the first one seems correct in the readme but was wrong in the .csproj file.
