### ISSUE TITLE
The example url in Readme is incorrect

### ISSUE THREAD

**Issue by XiaoFaye** [wp-net/WordPressPCL#15]
example in readme: `var client = new WordPressClient("http://demo.wp-api.org/wp-json/wp/v2/");`

The library is adding **wp/v2** to the url again, which cause 404 error:

![image](https://user-images.githubusercontent.com/6334728/27265214-7aa43042-54e5-11e7-9830-1428012d75f1.png)

**Comment by ThomasPe** [comment]
You're right, this has been changed recently. I've updated the sample code, thanks for pointing it out!
