### ISSUE TITLE
Cannot use with HTTPS protocol

### ISSUE THREAD

**Issue by FantacciSimone** [wp-net/WordPressPCL#150]
Hi,
I ' trying to use your library to call a REST API on HTTPS WP site.
I managed to succesfully integrate WordpressPCL with HTTP Protocol, but when I try to use it with HTTPS protocol I obtain the following error
_System.Net.WebException: Request cancelled: Unable to create a secure SSL / TLS channel_

This is the code I wrote (VB.NET)
`Dim client = New WordPressClient(enteconfig.UrlWordpress_Enteconfig + "wp-json/")
		client.AuthMethod = AuthMethod.JWT
		Await client.RequestJWToken(enteconfig.AdminUserWP_Enteconfig, enteconfig.AdminPasswordWP_Enteconfig)`

then I tried to write before this function call
`Net.ServicePointManager.SecurityProtocol = Net.SecurityProtocolType.Tls12`

but the error I gained is this
_Authorization header malformed._

How should I do to use WordpressPCL with HTTPS Protocol?
Thanks in advance,
Simone

**Comment by FantacciSimone** [comment]
For your knowledge in the end I had to add this:
`'HTTPS SSL
		System.Net.ServicePointManager.ServerCertificateValidationCallback = (Function(sendr, cert, chain, sslPolicyErrors) True)
		'abilito esplicitamente il protocollo tls 1.2 per framework inferiore alla 4.7
		If HttpRuntime.TargetFramework < New Version(4, 7) Then
			Net.ServicePointManager.SecurityProtocol = Net.SecurityProtocolType.Tls12
		End If`
As you can see, the problem was related to the Framework.

**Comment by ThomasPe** [comment]
Thanks for the info! Unfortunately I've never worked with VB. Is there anything we can change in the library to make this more seamless?

**Comment by FantacciSimone** [comment]
Unfortunately I do not think so, I posted this information for any other users who had the same problems.
Thanks for the library, it's really useful!
