### ISSUE TITLE
await client.IsValidJWToken() times out - no error messages?

### ISSUE THREAD

**Issue by toby11** [wp-net/WordPressPCL#154]
Hi,

I am trying to connect to a fresh install of Wordpress and all functions just seem to time out - is there no error reporting in this library?

```
await client.IsValidJWToken()
await client.Posts.GetAll();
```

both just seem to hang?

I have added this into my wordpress config 

define('JWT_AUTH_SECRET_KEY', 'xxx');

and going to http://mydomain.co.uk/wp-json/ returns valid json?

thanks

**Comment by toby11** [comment]
(tested with 1.51 and 1.6.1 from Nuget)

**Comment by ThomasPe** [comment]
have you tried calling your apis manually (e.g. using Postman) to see if the endpoints all work for you?
there are some cases where exceptions are thrown, but those might not cover all cases. 
are you able to share the link to your site?

**Comment by toby11** [comment]
@ThomasPe From a fresh test install of wordpress, its now working fine - maybe was an issue with the other test site. I will investgate to see the differences between them. 

thanks anyway!

**Comment by ThomasPe** [comment]
cool, good to hear!
