### ISSUE TITLE
Support Net 4.5 outside of netstandard

### ISSUE THREAD

**Issue by ri0ter** [wp-net/WordPressPCL#155]
Hey, what do you think about supporting net45 as an additional TargetFrameworks and allow lower version of Newtonsoft.Json?
My problem is that I'm using net 4.5 and cannot install WordPressPCL because I'm using Newtonsoft.Json version 6.x (cannot upgrade due to many other dependencies relying on it).

I've already tested that solution (with a lower version of Newtonsoft.Json as a conditional dependency) and it works fine.

**Comment by ThomasPe** [comment]
I haven't really looked into supporting additional TargetFrameworks, but I'd gladly look at a PR if this can be done easily without impacting other frameworks.

**Comment by ri0ter** [comment]
I've tested it again and noticed that I've been using wrong version (few commits behind master).
In #147 there was a change that breaks older versions of Newtonsoft.Json.
So at this point, I think you can close this issue.
