### ISSUE TITLE
Problem to create a page with template / meta

### ISSUE THREAD

**Issue by p3t3rBl4ck** [wp-net/WordPressPCL#161]
Hi,

thanks for that library. I want to create a page with a template, meta description and meta title but the app go an exception "not parameter included". I can see that Page model contains a "template" field and "meta" field. 

¿Can I do it?

thanks!

**Comment by polushinmk** [comment]
@p3t3rBl4ck it is interesting WP rest api feature, but you should set a php file template name
for example:
```c#
var page = new Page()
            {
                Title = new Title("Title 1"),
                Content = new Content("Content PostCreate"),
                Template = "page-about.php"
            };
var createdPage = await _clientAuth.Pages.Create(page);
```
