### ISSUE TITLE
Application/octet-stream MIMEType

### ISSUE THREAD

**Issue by Arendhal** [wp-net/WordPressPCL#162]
Could you add the application/octet-stream MIMEType?
This could be very useful if we want to upload .kmz and .kml files to our wordpress in order to add a layer to a GoogleMap map.
Currently this extension and MimeType does not exist in the MimeTypeHelper and kmz files are marked as text/plain which prevent normal usage of the file.

**Comment by ThomasPe** [comment]
Hey, feel free to add a pull request for this! :)
