### ISSUE TITLE
How to insert User meta?

### ISSUE THREAD

**Issue by eBenassati** [wp-net/WordPressPCL#163]
Hi, thank for that library!

I did not really understand the structure of the meta parameter. 
Could you please give me an example of it?

i' m trying to insert a new user. I create this function 

```        private static async Task InserUser()
        {
            WordPressClient client = await GetClient();
            var isValidToken = await client.IsValidJWToken();
            if (isValidToken)
            {
                var newUser = new User("example", "example@example.it", "password")
                {
                    FirstName = "examplename",
                    LastName = "examplesurname",
                    NickName = "nick",
                    Meta = ????
                };
                Console.WriteLine("Start");
                var insUser = await client.Users.Create(newUser);
                Console.WriteLine("Done");
            }
        }
```

but i don' t know how insert "Meta". I must insert that beacuse i use Ultimamate Member plugin and all extra information of a user are insert as meta.

What am i doing wrong?

Thanks for the attenction.

**Comment by ThomasPe** [comment]
Is this still an issue?

**Comment by hbcondo** [comment]
Yes, I created the same issue before this one per https://github.com/wp-net/WordPressPCL/issues/160

**Comment by LSparkzwz** [comment]
I'm also in the same situation, I tried doing something like this but it doesn't work:
`Meta = 
{
meta_field1 = "something1",
meta_field2 = "something2"
}`
Assuming the field names are the ones you can read in the database, how can I structure this meta field correctly?

**Comment by hbcondo** [comment]
@ThomasPe, this is still an issue. Would you please review and provide us your feedback? Thank you.

**Comment by nkuDev** [comment]
I'm having the same Problem :/ Did someone find a solution for it ?

**Comment by nkuDev** [comment]
@hbcondo I found a solution for it, what you need to do is to set up the register_meta in your "function.php". And then just simply do it like i did it in the Image
![WordPress MetaDaten](https://user-images.githubusercontent.com/50398266/66578879-2cb45a80-eb7c-11e9-9b89-b713bfb791fe.png)

I hope i could help you.

**Comment by ThomasPe** [comment]
@hbcondo @LSparkzwz @eBenassati did this solution work for you?

**Comment by hbcondo** [comment]
Is there a way to add / edit user meta data using only WordPressPCL?

**Comment by carlford10s** [comment]
This worked for me:

Create a class with the fields to work with:

        public class UserMeta 
        {
            public string _full_name { get; set; }
            public string _company_name { get; set; }
            public string _company_website { get; set; }
        }

Then create an instance of the WordPressPCL.Models.User Class

                var wpUser = new WordPressPCL.ModelsUser();

Populate non-meta fields for example:

                wpUser.Email = Input.Email;
                wpUser.FirstName = Input.FirstName;

The create an instance of the wpUser.Meta class using the UserMeta class defined above and populate those fields:

                wpUser.Meta = new UserMeta()
                {
                    _company_name = Input.CompanyName,
                    _company_website = Input.CompanyWebsite,
                    _full_name = Input.FirstName + " " + Input.LastName
                };

This works because the Meta object within the WordPressPCL.Models.User class is defined as dynamic.

Now you can create or update the record (to update define the Id field of the user.

                User wpRespond = new User();
                try 
                {
                    client.JsonSerializerSettings = new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore };
                    wpRespond = await client.Users.Create(wpUser);
                }
                catch (WPException wpex)
                {
                    //var name = wpex.BadRequest.Name;
                    //var message = wpex.BadRequest.Message
                    //var wpex.BadRequest.Data
                    throw wpex;
                };

Hope this helps

**Comment by Daraciel** [comment]
Hi i tried @carlford10s solution but it doesnt work for me. Has something changed since 2020?

**Comment by masgh021** [comment]
Hi @Daraciel @carlford10s   this doesn't worked for me , do you find other solution ?
I want add/delete/edit new record in usermeta table , 
How is it possible ?
