### ISSUE TITLE
Title not rendered / encoded correctly

### ISSUE THREAD

**Issue by Suplanus** [wp-net/WordPressPCL#167]
If i get the posts of [this page](https://festival-holledau.de/) there are titles like `„SKYLINE GREEN“ RUNDET SAMSTAGSPROGRAMM AB` which are not encoded correctly. 
In `Title.Rendered` I get `&#8222;Skyline Green&#8220; rundet Samstagsprogramm ab`.

This is my workaround:

```csharp
var title = WebUtility.HtmlDecode(post.Title.Rendered);
```

Thanks for the great library! Rock on!

**Comment by ThomasPe** [comment]
The API will always return the encoded version to prevent the JSON from getting broken. I guess this is more of a design discussion than a bug. What do the users expect the library to do with the data returned from the API?

For now I would do as little transformations to the data as possible until / unless there are a lot of requests to change something.
