### ISSUE TITLE
CustomRequest.Create throws 'Cannot deserialize the current JSON array' exception

### ISSUE THREAD

**Issue by hbcondo** [wp-net/WordPressPCL#170]
When calling the `CustomRequest.Create` method, the following exception is thrown:

_Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'BPGroup' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath '', line 1, position 1._

Below is the code snippet that is experiencing this issue:

```c#
try
{
    var group = client.CustomRequest.Create<BPGroup, BPGroup>("buddypress/v1/groups", new BPGroup() { name = name, slug = slug, description = desc, creator_id = 1 }).Result;
}
catch (Exception ex)
{
    Console.Error.Write("This is where the exception occurs");
}

public class BPGroup
{
    public string name;
    public string slug;
    public string description;
    public int creator_id;
}
```

HTTP Request:
```cURL
POST https://domain.local/wp-json/buddypress/v1/groups HTTP/1.1
Authorization: Bearer [key]
Content-Type: application/json; charset=utf-8
Host: [domain]
Cookie: PHPSESSID=[value]
Content-Length: 177

{"name":"my name","slug":"my slug","description":"my desc","creator_id":1}
```

HTTP Response:
```json
[
  {
    "id": 11,
    "creator_id": 2,
    "parent_id": 0,
    "date_created": "2019-04-03T23:08:07",
    "description": {
      "rendered": "<p>my desc</p>\n"
    },
    "enable_forum": false,
    "link": "my link",
    "name": "my name",
    "slug": "my slug",
    "status": "public",
    "avatar_urls": {
      "thumb": "https://domain.local/wp-content/plugins/buddypress/bp-core/images/mystery-group-50.png",
      "full": "https://domain.local/wp-content/plugins/buddypress/bp-core/images/mystery-group.png"
    },
    "_links": {
      "self": [
        {
          "href": "https://domain.local/wp-json/buddypress/v1/groups/11"
        }
      ],
      "collection": [
        {
          "href": "https://domain.local/wp-json/buddypress/v1/groups/"
        }
      ],
      "user": [
        {
          "embeddable": true,
          "href": "https://domain.local/wp-json/buddypress/v1/members/2"
        }
      ]
    }
  }
]
```

**Comment by polushinmk** [comment]
@hbcondo seems that responce type is not simple BPGroup but an array of BPGroup. Trt to change return type like this
```c#
var group = client.CustomRequest.Create<BPGroup, BPGroup[]>("buddypress/v1/groups", new BPGroup() { name = name, slug = slug, description = desc, creator_id = 1 }).Result;
```

**Comment by hbcondo** [comment]
@polushinmk, thank you for your reply. I think your suggestion worked in that the JSON serialization exception isn't being thrown using the array return type but a new exception is being thrown:

_Unexpected character encountered while parsing value: {. Path '[0].description', line 1, position 93._

I guess the `description` property in the response is causing this since it's a json object and WordPressPCL / Newtonsoft isn't expecting this type? If so, any suggestions on how to handle it? Thanks again.

![image](https://user-images.githubusercontent.com/306958/55749798-b41ae880-59f6-11e9-8ac9-e5f93e881221.png)

**Comment by polushinmk** [comment]
@hbcondo you are right, this is an object instead of string.
For this case you can create separate object for output. So you will have 2 objects: BPGroupInput and BPGroupOutput (for example)
```c#
client.CustomRequest.Create<BPGroupInput, BPGroupOutput[]>
```
description is a simple object with 1 property named "rendered"
```c#
class Description {
    string rendered {get;set;}
}
```

**Comment by hbcondo** [comment]
Great, this approach worked; thanks again for reviewing and providing code snippets. I'm closing this issue, the exceptions experienced were not specific to WordPressPCL or Newtonsoft.
