### ISSUE TITLE
how to use post with media

### ISSUE THREAD

**Issue by gandol2** [wp-net/WordPressPCL#171]
I want to insert the media into the post.
With HTML tags ..

Please give us an example.

**Comment by polushinmk** [comment]
[How to upload Media](https://github.com/wp-net/WordPressPCL/wiki/Working-with-Media#create-new-media)
[How to create Tag](https://github.com/wp-net/WordPressPCL/wiki/Working-with-Tags#create-new-tag)

after this you can create Post
```c#
var post = new Post() {
    Tags = new int[] { tagId }, //id of created tag
    //path to uploaded image
    Content = new Content($"content text with html tags. you can insert image like this <img src =\"{IMAGE_PATH}\" />"),
   //any other post properties
}
//create post
await client.Posts.Create(post);
```

**Comment by gandol2** [comment]
1. Upload the image.
2. Get the path to the image.
3. Enter the content and image path in HTML.

Is this the same sequence?

**Comment by polushinmk** [comment]
Same. Create Media method returns you created media object. You can try it all on your site

**Comment by gandol2** [comment]
thank you. i have another question.

how to get image size (with and height)?

when i post content including image, i want to include size information.

**Comment by polushinmk** [comment]
created Media object has property **MediaDetails** of type MediaDetails which has properties Width, Height (and all kind of Sizes).
you can find it in out codebase
[MediaItem](https://github.com/wp-net/WordPressPCL/blob/master/WordPressPCL/Models/MediaItem.cs)
[MediaDetails](https://github.com/wp-net/WordPressPCL/blob/master/WordPressPCL/Models/MediaDetails.cs)

**Comment by gandol2** [comment]
i see. thank you :)
