### ISSUE TITLE
Cannot get "Unpublished" Post using GetByID

### ISSUE THREAD

**Issue by SocialNetUsr** [wp-net/WordPressPCL#173]
Hi to all,

I'm trying to publish an unpublished post but the GetByID returns "Sorry, you are not allowed to do that." After some investigation i founded that the plugin cannot get posts that are in **unpublished** status. Any ideas?? 

`var post = await client.Posts.GetByID(9999);`
`post.Status = Status.Publish;`
`post.Date = DateTime.Now;`
` var updatedPost = await client.Posts.Update(post);`

**Comment by ThomasPe** [comment]
Yes, you need to have valid JWT token for an authorized user to get unpublished posts.

**Comment by SocialNetUsr** [comment]
i'm using  the below command which returns true.  What else can i check ??
` await client.IsValidJWToken();`

**Comment by ThomasPe** [comment]
that should technically do it. Are you using a user that has the correct permissions to access unpublished posts?

**Comment by SocialNetUsr** [comment]
my user has Administrator role
i have try almost all available methods without luck 

- GetAll()
- GetPostsByCategory()
- Query()

**Comment by polushinmk** [comment]
@SocialNetUsr try
```c#
var post = await client.Posts.GetByID(9999, useAuth: true);
```

**Comment by SocialNetUsr** [comment]
bloody great, it's working!!!  I didn't check this constructor.... 
Thanks all for the help!!!
