### ISSUE TITLE
Apache Module mod_auth_basic

### ISSUE THREAD

**Issue by matthijssmeets** [wp-net/WordPressPCL#174]
What a great tool.

I can't manage to connect to a website protected by HTTP Basic Authentication. Does anyone have a solution for that?

**Comment by ThomasPe** [comment]
The support for basic authentication was removed a while back due to the unsafe way it was implemented back then. Perhaps we could look into supporting this again, @polushinmk  thoughts?

**Comment by polushinmk** [comment]
According to https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/ Basic Authentication is not recomended to use by WP REST API developers. I think we shouldn`t add support of it to core but may be we should refactor our authentication mechanism to provide an ability to extent it with own implementations

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!
