### ISSUE TITLE
please consider adapting the plugin to unity 2019

### ISSUE THREAD

**Issue by freddymx** [wp-net/WordPressPCL#175]
please consider adapting the plugin to unity3d 2019

**Comment by ThomasPe** [comment]
not really sure what that means exactly tbh

**Comment by freddymx** [comment]
I wanted to say that if it is possible to port the library to work with Unity3d.

**Comment by ThomasPe** [comment]
I'm not sure I understand the requirements so the library "works with Unity3d". What would I need to change?
