### ISSUE TITLE
How to get objects by post type or taxonomy

### ISSUE THREAD

**Issue by rubenTDV** [wp-net/WordPressPCL#176]
I'm trying to get the objects with a specific post type or taxonomy, not a entire page, nor a post from a blog, only the website objects that have an specific post type.

For example, in my web site I have a "news" post type with "rutes" and "metereology" taxonomies, but I don´t know how to extract those objects.

Thanks!!

**Comment by ThomasPe** [comment]
Although it's not documented in the official REST API Handbook it seems it's possible to filter posts by custom taxonomies like this:
https://www.timrosswebdevelopment.com/filter-wordpress-rest-api-by-taxonomy-slug/

So you could try to use the CustomRequest method and manually specify the correct REST path:
https://github.com/wp-net/WordPressPCL/wiki/CustomRequest

Hope this helps.
