### ISSUE TITLE
Add Status.Trash to a post

### ISSUE THREAD

**Issue by philippdolder** [wp-net/WordPressPCL#177]
The Status of Trash for a Post is missing. 
The official REST API docu does not mention it (yet), but in reality trashed posts are in status trash in the response. Tried with WordPress 5.1.1.
https://developer.wordpress.org/rest-api/reference/posts/#retrieve-a-post

**Comment by ThomasPe** [comment]
Care to open a Pull Request for this? :)

**Comment by tamper2** [comment]
Added pull request #206 for this issue! :)

**Comment by ThomasPe** [comment]
Merged 
https://github.com/wp-net/WordPressPCL/pull/206
