### ISSUE TITLE
Structure reorganiztion

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#18]
Hello!
I think that using the library in this form:
```
Wordpressclient.Posts instead of wordpressclient.ListPosts ()
Wordpressclient.Posts.GetByXXX ()
Wordpressclient.Posts.Create (Post post)
Wordpressclient.Posts.Update (Post post)
Wordpressclient.Posts.Delete ()
```
More convenient and understandable than `wordpressclient.ListPosts (), wordpressclient.CreatePost, wordpress.UpdatePost`

Same for Comments, Categories and other

To do this, you need to create a group of classes, such as PostsOperations, CommentsOperations, CategoriesOperations, and others, which you can inherit from the 
`ICRUDOperation <T>` interface that will declare all common methods such as `Create (T item), Update (T Item), Delete (T item)`
In the main class, it will be necessary to create several properties that will grant access to these classes.

If this is interesting, then I can create a pull request with the code to show how the Posts object looks like after this

**Comment by ThomasPe** [comment]
I definitely like the idea of getting more structure into this project. 
We should do this in a separate branch so we can easily test the idea and merge it back once it really is ready.
I'd also appreciate feedback on this from others involved using this project. :-)

**Comment by polushinmk** [comment]
Ok!
I forked your master branch and can do this job in my forked branch and then you merge my work with your **reorg-methods** branch? Or how we should organize this process? I am novice on git and dont know this as I would like :)

And other question: should we maintain backward compatibility with current code structure (by save current methods and mark them as Deprecated) or we can break compatibility and move all code to the new structure?

**Comment by ThomasPe** [comment]
I'm pretty new to GitHub myself :D but yeah, that's how I would propose to do it! 

I think we should pass on backwards compatibility to get a codebase as clean as possible. Once the work is done it's gonna get a new major version number to indicate this breaking change.

**Comment by cobalto** [comment]
Yay! Yes, please!
Let's organize and call it 2.0 with break changes from the past o/
LET'S REWORK THE QUERY BUILDER TOO, PLEASE! 
This thing bugs me crazy with it's multiple responsability xD

**Comment by ThomasPe** [comment]
Indeed there should be a separate implementation of the query builder for each type since they also have different valid parameters

**Comment by polushinmk** [comment]
Hi everybody!
I did some work of structure reorganization. You can find it in my fork of this repo  [my repo](https://github.com/polushinmk/WordPressPCL)
Whats changed:
- Add ICRUDOperation interface (may be we should rename it to ICRUDOperationAsync ?)
- Add realization of this interface in this Classes: Posts, Comments, Tags, Users, Medias. I left Settings interaction code because there is only 2 methods: get and update. Not all CRUD operations
- Move Http interaction code to separate HttpHelper class
- Add properties to WordpressClient class and move specific code to Posts, Comments and other classes
- Remove Username and Password for security reasons. In my opinion it should not be stored as fields of main class.
- Move JWToken to httpHelper class and so hide it from public access. Not for security reason, so we should discuss about restore the public access to JWToken
- Rewrite  tests to be compatible with new implementation
- Add some new overloaded methods
- Replace Array usage to IEnumerable but we can discuss about it.

What, I think, we can do next:

- [ ] Review it

- [ ] Test it

- [ ] Discuss and make changes

- [ ] Add missing classes and properties to the base entity classes to be 100% compatible with WP REST API Handbook

- [ ] Remove PostCreate and CommentCreate class. They no longer need

- [ ] Add missing XML comments to be 100% code comments coverage

- [ ] Review the QueryBuilder and more and more and more

And so now some usefull scenarios how to use reorganization code:

```
            WordPressClient client = new WordPressClient("http://sample.com/wp-json/");
            //now username and password only in RequestJWToken
            await client.RequestJWToken("user", "password");

            //Yes, now we can enumerate entities in property
            foreach (Post post in client.Posts)
            {
                Console.WriteLine(post.Title.Rendered);
            }

            //And create Post like this
            await client.Posts.Create(new Post() { Title = new Title("Test Post!") });

            //And update like this
            Post p = client.Posts.First();
            p.Date = DateTime.Now;
            await client.Posts.Update(p);

            //And delete like this
            await client.Posts.Delete(p.Id);
```

I'm waiting for your feedback and ready for discussion :) 
Links to commits:
47f6603a01d1779b6e4aef2ad7ae2c1ad5a1566c
79c6bf10000540e33870b1814e17a8086e6eed64
8d50c6a34fcea4e7170f81abfc0fc89920cbf66d

**Comment by ThomasPe** [comment]
Thanks for your work! I haven't looked at it in detail yet, but here are a few thoughts (I will follow up tomorrow):

- we should separate the DTO Models from the client code so its easier to maintain.
- I'm not sure about having the client actually holding on to the data. IMO it should only be a Service an talk to the API and not act as a repository. This should be handled outside of the pcl. 
-  I don't think we can remove PostCreate and CommentCreate just yet since the API does not support creating these with the Content inside the Raw Property but expects a simple string.
- Media is already plural, no s needed. Another reason to separate DTO classes from the client code.

What do you think? Feel free to PR on the new branch if you want help coding ;-)

**Comment by polushinmk** [comment]
- What do you mean? We already have DTO models (Post, Comment, Tag, Category etc) without any logic. only clean class with properties mapped to wordpress JSON Schema. Create, Update, Delete, get and other logic separate from model and placed in Posts, Comments, Tags etc classess (may be name it "operation" classes).  So we can change DTO model without change "operation" class. 
- And now it is only a service but with more "sugar" and use some powerfull features from C# and .NET library like IEnumerable, LINQ etc. So Create method from this library actually mapped to POST HTTP method on WP REST API but it looks more objective and more familiar to use for c# users.
- I made some changes in my last commit 0da0d477a502a50c52dc3e2e4e3e6486955c04d2  which fixed creation Post and Comment from objects schema. So now we really can remove PostCreate and CommentCreate classes. I test it and it works! Only one DTO model for all purposes without hacks :)
- Yeah, Medias sounds innormal but it must be naming convention. Or we can choose another naming convention or exclude Media from this.

I alse made some work in my last commit. Reorganize fie structure of project, fix some problems, add Categories and Pages. Later I will create PR on your reorg-structure branch.

**Comment by ThomasPe** [comment]
- sorry, I probably was looking at an old commit
- I agree with all the nice c# features, I just don't think the client should cache the data (client.Posts <= this shouldn't be used like a method). `Wordpressclient.Posts.Get()` would be more coherent.
- Looking forward to trying that, I'll test it once you're ready with your PR.
- I think using the regular English plural is a good naming convention where Media would be just fine

**Comment by ThomasPe** [comment]
awesome work, thanks! will clone it and start helping you with tests etc.

**Comment by ThomasPe** [comment]
since we agreed on a new structure the next steps will be planned here #24 with specific features like the QueryBuilder #24 having their own issues, all marked with Milestone 1.0.
