### ISSUE TITLE
How to use MediaQueryBuilder to retrieve a item by filename?

### ISSUE THREAD

**Issue by franknesse** [wp-net/WordPressPCL#181]
I would like to query for media items by file name. I have tried using the Filter property of the MediaQueryBuilder in several ways, but in all cases it looks like the filter is not applied. Presumably because I am using the wrong syntax or trying to do something which is technically impossible. I have googled for some Filter examples but so far no hits. 

Below is my code (which returns the very first item in the media gallery, despite what filter I apply)

```
var queryBuilder = new MediaQueryBuilder();
queryBuilder.PerPage = 1;
queryBuilder.Page = 1;
queryBuilder.Filter = $"file={fileName}";				
var media = await client.Media.Query(queryBuilder);
```
Any pointers?

Thanks in advance!

**Comment by franknesse** [comment]
Solved. In the meantime I found out that what I want I can do by setting the Search property of the quierybuilder to the filename:

```
var queryBuilder = new MediaQueryBuilder();
queryBuilder.PerPage = 1;
queryBuilder.Page = 1;
queryBuilder.MediaType = MediaQueryType.Image;				
queryBuilder.Search = fileName;				
var media = await client.Media.Query(queryBuilder);
```

**Comment by TylerByte666** [comment]
Can't call it solved if there was no issue in the first place.

**Comment by ThomasPe** [comment]
@franknesse thanks for sharing your solution to this, sorry I couldn't get back to you earlier.

**Comment by TylerByte666** [comment]
@franknesse Sorry was replying to the wrong thread

**Comment by muneernet** [comment]
> I would like to query for media items by file name. I have tried using the Filter property of the MediaQueryBuilder in several ways, but in all cases it looks like the filter is not applied. Presumably because I am using the wrong syntax or trying to do something which is technically impossible. I have googled for some Filter examples but so far no hits.
> 
> Below is my code (which returns the very first item in the media gallery, despite what filter I apply)
> 
> ```
> var queryBuilder = new MediaQueryBuilder();
> queryBuilder.PerPage = 1;
> queryBuilder.Page = 1;
> queryBuilder.Filter = $"file={fileName}";				
> var media = await client.Media.Query(queryBuilder);
> ```
> 
> Any pointers?
> 
> Thanks in advance!

Hi ,

Could you please let me know how to query a directory from media and fetch pdf files using c# Web Api
