### ISSUE TITLE
no route was found

### ISSUE THREAD

**Issue by digitxo** [wp-net/WordPressPCL#185]
public static string WordPressUri = "https://www.balancingpawsdogtraining.com/wp-json/";

This is my WordPressURI 

This is my error:
No route was found matching the URL and request method

It happens here:

            var client = new WordPressClient(ApiCredentials.WordPressUri)

            {

                AuthMethod = AuthMethod.JWT

            };

            await client.RequestJWToken(ApiCredentials.Username, ApiCredentials.Password);

(on the REquestJWToken call)

**Comment by ThomasPe** [comment]
Have you set up the JWT plugin correctly?

**Comment by ThomasPe** [comment]
Closed due to inactivity
