### ISSUE TITLE
How to update a Media content (image)

### ISSUE THREAD

**Issue by jacargentina** [wp-net/WordPressPCL#188]
I'm looking for a way to UPDATE the image contents for an existing Media item on the library. Is I possible? (The `Media.Update` doesn't seem to support that?)

**Comment by polushinmk** [comment]
@jacargentina As I know you cannot update image using wordpress admin, so you cannot update it using restp api

**Comment by ThomasPe** [comment]
no, you will have to delete the item and upload a new one as @polushinmk said.
