### ISSUE TITLE
Cannot GetByID() on a private post

### ISSUE THREAD

**Issue by dapug** [wp-net/WordPressPCL#192]
GetPost by ID works fine for published posts (authenticated or not), BUT if the post is not published, I get a 401.

`await client.Posts.GetByID(postID);`

I have a valid auth token, as IsValidJWToken() returns true after signing in and getting the token.
`var isValidToken = await client.IsValidJWToken();`

The user is an admin, it's not a permissions issue in WP.

**Comment by ThomasPe** [comment]
sorry for the late reply. Have you tried if you can get the post directly through the REST API?

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!
