### ISSUE TITLE
Can't find Json.Newtonsoft 12.0.1 

### ISSUE THREAD

**Issue by jupagose** [wp-net/WordPressPCL#194]
I tried for hours with nugget package 1.6.2, But it doesn't work. "Can't find Json.Newtonsoft 12.0.1 file" was the problem.

I changed Json to 11.0.1  and now it works. Good to get it from nugget instead to must recompile.

Tks.

**Comment by ThomasPe** [comment]
hey, just so I understand your problem a bit better - what's stopping you from upgrading to Json.Newtonsoft 12.01+?

**Comment by jupagose** [comment]
I'm on 12.0.3 but PCL doesn't seems to recognize it, even I downgraded to 12.0.1 and problem persists,   That's why i recompiled PCL pointing to 11.0.1.

**Comment by ThomasPe** [comment]
I downgraded the JSON.NET dependency to 11.0.1 and created a new release (1.7.0), perhaps you can try if this one works for you.

**Comment by jupagose** [comment]
@ThomasPeThoma It works. Tks
