### ISSUE TITLE
How to get all posts created by an author with a given id?

### ISSUE THREAD

**Issue by navjot50** [wp-net/WordPressPCL#205]
I want to get all the posts that are created by a given author. The function GetPostsByAuthor in the Posts class just gives the the first 10 posts by a given author. Also the method GetAll which the Posts class inherits from CRUDOperation class gets all the posts regardless of any filtering on the basis of author id.

Another thing is that we cannot get the response headers as the requests are executed internally by the HttpHelper classes, so there is no way to determine how many X-WP-TotalPages are there.

One ugly workaround that i found out is:

```
  public async Task<List<Post>> GetAllPostsForGivenAuthor(int authorId) {
      int pageNum = 1;
      var postQueryBuilder = new PostsQueryBuilder() {
        Page = pageNum,
        PerPage = Constants.WordpressConstants.PerPage,
        Authors = new int[] { authorId },
        OrderBy = PostsOrderBy.Date
      };

      var postsByAuthor = new List<Post>();
      while (true) {
        try {
          var queryResult = await wordpressRestClient.Posts.Query(postQueryBuilder);
          postsByAuthor.AddRange(queryResult.ToList());
          postQueryBuilder.Page = ++pageNum;
        } catch (WPException) {
          break;
        }
      }

      return postsByAuthor;
  }
```

I don't like the fact that we have a while loop on true and that we have to expect an exception to break the loop. Is there a better way to do this?

**Comment by ThomasPe** [comment]
Instead of breaking on an exception you can check if you get as many posts as you're expecting. By default the API will return a max. of 10 posts, but you can set that to a maximum of 100 which should already reduce the amount of requests dramatically.

Returning the X-WP-TotalPages might be something to look at, would need to think about how to best provide this without cluttering the response.

**Comment by navjot50** [comment]
Yes, I ended up doing the same as you suggested.
