### ISSUE TITLE
Language parameter in posts query

### ISSUE THREAD

**Issue by rlubkowski** [wp-net/WordPressPCL#209]
I've noticed that there's no option to query posts with "lang" parameter is there a way to do it?

**Comment by ThomasPe** [comment]
hey, this sounds like this is a plugin-specific feature?

**Comment by rlubkowski** [comment]
Well, I guess it is... Regardless, I think it would be a nice feature to add possibility to append custom query parameters.

**Comment by ThomasPe** [comment]
what plugin are you using for multilang?

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!
