### ISSUE TITLE
Tests Stucture

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#21]
Since most of the work has been done for the big restructuring I started looking at the tests and would like to propose a general structure.

Each of the entity extensions for the client will get it's own test class, so
```
Posts_Tests.cs
Comments_Tests.cs
Tags_Tests.cs
...
```

Each test class will contain tests for the CRUD-Implementation plus additional tests that might make sense. Test names will be prefixed by the entity so the list of tests in the Test Explorer is more structured. I also propose to drop the _Tests suffix as they seem unnecessary to me.
So each test class will have at least these methods

```
[TestMethod]
Posts_Create()
Posts_Read()
Posts_Read_Single() // not sure about the naming, maybe Posts_Read_ByID?
Posts_Update()
Posts_Delete()
```

Thoughts?

**Comment by polushinmk** [comment]
Yeah! I think you are right/

**Comment by ThomasPe** [comment]
All posts are now green for me :-)

**Comment by polushinmk** [comment]
Great work! It looks like the library is really ready for release

**Comment by ThomasPe** [comment]
Tests have been completed for existing methods. Next step would be to remove or rename those that don't fit the new structure.
