### ISSUE TITLE
Images Within Posts

### ISSUE THREAD

**Issue by raymond-dillon** [wp-net/WordPressPCL#212]
Hi,

I'm pulling post content down no problem. However if the post contains an image, it does  not appear under content.rendered. 

How do I view the embedded image within the post?

Thank you for your time!

**Comment by ThomasPe** [comment]
Does it appear in the JSON response when you call the API directly, e.g. with Postman? This seems to be an API issue rather than one with the library.

**Comment by raymond-dillon** [comment]
I just checked and it appears in Postman under content.rendered with the <img> tag, but when I hit the breakpoint in VS2019, all that displays for the post is the text.

i.e Postman shows 

Text 

Image 

Text 

VS2019 shows 

Text 



Text

**Comment by ThomasPe** [comment]
in the rendered part as well?

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!
