### ISSUE TITLE
Support jwt-auth

### ISSUE THREAD

**Issue by christianfrick** [wp-net/WordPressPCL#214]
Dear all
I'd like to contribute the support for the plugin https://wordpress.org/support/plugin/jwt-auth/ since the original plugin https://wordpress.org/support/plugin/jwt-authentication-for-wp-rest-api/ seems to be obsolete and not maintained anymore.
I do already have a working code. Where shall I commit it to? Can you please create me a branch for the PR?
Cheers
Christian

**Comment by ThomasPe** [comment]
Hey, cool stuff! Feel free to create a PR against the master branch. We do need to make sure that we don't break the old auth way, though.

**Comment by christianfrick** [comment]
Hi @ThomasPe 
It seems like you first need to create a branch on which I can push my changes on. Can you please create `jwt-auth-support` for me? Thanks

**Comment by ThomasPe** [comment]
I can create a branch, no problem. But have you tried forking the whole project and making a PR from there after you added your changes? Should be the easiest way and how it's usually done.

**Comment by christianfrick** [comment]
All fine. I'm just not used to GitHub. The PR #216 is available, but testing which supports both plugins is not implemented yet. Please find more details in the PR description.

**Comment by topcatarg** [comment]
Do you need help wih this? I saw that the last PR was rejected... What else do you need for this to work?

**Comment by ThomasPe** [comment]
Hey, the PR didn't pass the integration tests yet as we have to adjust those for the new code. That means the WordPress docker installation that the code is being tested against needs to be adjusted as well. I'll look into it, but can't make any promises how fast I can do it. Feel free to look at it yourself as well. 
https://github.com/wp-net/wordpress-docker-compose

**Comment by lkenner** [comment]
Hey buddies,
is is integrated yet? Half of the code looks like it but doesn't work at me :/
Still get the error which #213

**Comment by ThomasPe** [comment]
It's on nuget now, sorry for the delay!

**Comment by christianfrick** [comment]
Awesome, thanks a lot @ThomasPe

**Comment by bajecogem83** [comment]
Thank you ☺️
