### ISSUE TITLE
Error when uploading images

### ISSUE THREAD

**Issue by lkenner** [wp-net/WordPressPCL#226]
Hi,

I'm facing an issue after uploading an image to Wordpress via Media.Create().
I'm receiving: 
> Error converting value "" to type 'WordPressPCL.Models.OpenStatus'. Path 'comment_status', line 1, position 465.

It seems like it's returning an empty value for the Status of comments.

BTW: the image is uploaded successfully!

Has somebody a workaround?

Thanks

**Comment by ThomasPe** [comment]
Interesting, do you have any settings or plugins configured that might interfere with this? Haven't seen this issue yet myself.

**Comment by ThomasPe** [comment]
I’m closing this issue because it has been inactive for a while. Please feel free to reopen if you still encounter this issue. Thanks!

**Comment by mirasolutions** [comment]
Hello, i have the same error, have you a solution ?

**Comment by lkenner** [comment]
> Hello, i have the same error, have you a solution ?

Boy that was two years ago.. the project I used it for has failed multiple times since that..

**Comment by mirasolutions** [comment]
ok
