### ISSUE TITLE
List categories? 

### ISSUE THREAD

**Issue by CDrosos** [wp-net/WordPressPCL#23]
I see there isnt a method to do that. The proper way to do something like this is first to list all posts and then to get the categories from the posts?

**Comment by ThomasPe** [comment]
No, that would be way top much work.
There's an API endpoint for getting all Categories, ist's just not yet implenented in this tool.
http://demo.wp-api.org/wp-json/wp/v2/categories

You can either build it yourself and add a PR to the current implementation or wait for the reworked client which will suppor getting categories (See reference).

**Comment by CDrosos** [comment]
i would love to contribute, i will try as i havent done it before, i have create here a helpful method for the category creation https://github.com/wp-net/WordPressPCL/pull/25 is all ok with this?

**Comment by ThomasPe** [comment]
hey, thanks for taking the time. can you create a single pull request for all your changes so I can check the more easily?

**Comment by CDrosos** [comment]
im not sure what that means :D how i can do that? i believe at that point a how to contibute tutorial is what i need

**Comment by ThomasPe** [comment]
there are quite a lot of those around the web ;-) 
when you look at the pull requests, there are 3 different ones created by you for each commit you've created. you should be able to delete those and create a single one for all the changes you've added.

**Comment by CDrosos** [comment]
something tells me that i should create requests from visual studio, i have done it manually :D :D dont laugh

**Comment by ThomasPe** [comment]
creating Pull Requests from GH isn't bad, I do it that way as well... Just don't PR after each commit

**Comment by ThomasPe** [comment]
also your PR is missing Unit Tests ;-)

**Comment by CDrosos** [comment]
Will do soon :)

**Comment by CDrosos** [comment]
I have just added the Tests https://github.com/wp-net/WordPressPCL/pull/28 :)

**Comment by ThomasPe** [comment]
Pls merge everything into one PR ;-)

**Comment by CDrosos** [comment]
so i should delete everything and do it all again and only press merge in the end? i cvant find a way the merge the already pr's

**Comment by ThomasPe** [comment]
yea, I think you just have to cancel / delete the existing PRs

**Comment by CDrosos** [comment]
i cant find how i can combine them, i will try to build them again in the future although it shouldnt be so hard to combine merges. i have a lot of merge bases and i cant combine them all to one

**Comment by ThomasPe** [comment]
When you create a new pull reqeust it should include all commits by default, not sure you'll have to combine anything yourself

**Comment by polushinmk** [comment]
Hi @CDrosos !
I see that you created 4 branches: 1 per PR. You should now merge it all in 1 branch (may be in master, or create new, or your decision) in your forcked repo and after that you can create a one PR with all your commits from your branch to wp-net master branch.
You dont need to create new branch for new PR. you can do all your work in 1 your branch

**Comment by CDrosos** [comment]
i think i have made it, check here please https://github.com/wp-net/WordPressPCL/pull/34

**Comment by CDrosos** [comment]
where is the best place to post questions about this package? for example im trying to get the title of a post using

var posts = await client.Posts.GetPostsByCategory(categoriesData[e.Position].CategoryId);
            var postsList = posts.ToList();
            showingCategories = false;
            postsData = new ObservableCollection<PostsItem>();
            foreach (var temp in postsList)
            {
                var dataItem = new PostsItem();
                dataItem.Name = temp.Title.ToString();
                dataItem.CategoryId = temp.Id;
                postsData.Add(dataItem);
            }

and i get "WordpressPCL.Title" instead of the title

**Comment by ThomasPe** [comment]
For questions you could either open a new issue or write a post on Stackoverflow and tweet me the link @th_p

It seems like you want the Posts as an ObservableCollection, right? Easiest way would be to create it like this:

var posts = await client.Posts.GetPostsByCategory(categoriesData[e.Position].CategoryId);
postsObeservable = new ObservableCollection<Post>(posts);

You should not need to create a List yourself since you can just foreach on the IEnumerable returned from the client.

**Comment by CDrosos** [comment]
My biggest issue was to get just the title of the post by using temp.Title.ToString();
now i see i should use temp.Title.Raw for that

**Comment by ThomasPe** [comment]
have you tried temp.Title.Rendered? Raw is usually empty except when using the edit-Context.
Same for the content afaik.

**Comment by CDrosos** [comment]
worked, thanks
