### ISSUE TITLE
Any interest in a front-end Razor Class Library to Interact with this?

### ISSUE THREAD

**Issue by taylorchasewhite** [wp-net/WordPressPCL#243]
Is this something you'd be interested in adding or being created? I'm open to doing the development in this package/repository or in a separate repository/package.

Ideally someone would be able to consume with the least amount of effort and I think a Razor Class Library would further that goal.

**Comment by ThomasPe** [comment]
I haven't worked much with Razor myself but if you think this would be a helpful tool I'm all for it! I think it would make sense to have it decoupled from this repo but I'd be happy to create a new one under the wp-net organization and add you as an admin if you like.

**Comment by taylorchasewhite** [comment]
I'm down to pursue that dynamic of a repo in the wp-net org. I actually just started one earlier today before you had written this [under the BlazingApple org](https://github.com/BlazingApple/Blog) (I had created this recently) but I'm down to move the blog consuming in a Razor Class Library under the wp-net org.

FWIW, here's an example of a "consumer" displaying it in a default Blazor App template:

![image](https://user-images.githubusercontent.com/3686217/103184184-cbfa6600-4884-11eb-8369-a0efc6ac2dde.png)

**Comment by ThomasPe** [comment]
Sure thing, what do you think the repo should be called?

**Comment by ThomasPe** [comment]
stale
