### ISSUE TITLE
Add parameter "useAuth" for CustomRequest.Create

### ISSUE THREAD

**Issue by tamper2** [wp-net/WordPressPCL#259]
For usage with custom plugins or php code.
For example, I'm trying to use this plugin: https://wordpress.org/plugins/bdvs-password-reset/
And I can't because all the requests are POST with no authentication headers. I've had to create my own HTTP POST method for this specific case.

Could change the signature of CustomRequest to be:
`public async Task<TOutput> Create<TInput, TOutput>(string route, TInput Entity, bool useAuth = true) where TOutput : class`

And pass useAuth to HttpHelper (like in Get method).

**Comment by navjot50** [comment]
The method you mentioned uses authentication headers by default, so there is no need of optional `useAuth` argument. What is the error message that you get?

**Comment by ThomasPe** [comment]
stale
