### ISSUE TITLE
What is the most effective way of adding new property to Post model?

### ISSUE THREAD

**Issue by piotrstarzynski** [wp-net/WordPressPCL#270]
Hello, I would love to include few additional fields to Post model. Mostly they are default ones as soon as you activate Yoast plugin (for example yoast_head).
How to add this to query and Post model?

**Comment by ThomasPe** [comment]
Easiest way for now would be to use the CustomRequest feature where you can provide your own post class implementation:

**Comment by piotrstarzynski** [comment]
It works like a charm. Thank You!
