### ISSUE TITLE
Remove Auth Properties from WordPressClient

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#291]
Since we're just exposing the Auth Settings of the Auth SubClient in the WordPressClient I propose we remove them and just make the properties inside the Auth client public.

Thoughts @navjot50?

**Comment by navjot50** [comment]
Yes, it was also my thought when I did some changes related to Auth. I can issue a PR for this.

**Comment by ThomasPe** [comment]
appreciated!
