### ISSUE TITLE
Return post url after create new post

### ISSUE THREAD

**Issue by sabershariat20** [wp-net/WordPressPCL#295]
Hi .
How to return and save content URL after creating new content ?

**Comment by navjot50** [comment]
The Wordpress REST API returns a json property called `Link` which is the link of the newly created resource. The library's model classes also have this `Link` property and you can access it via the model object of the created resource. You can save and return this property.

```
var createdPost = client.Posts.Create(post);
var link = createdPost.Link;
```

Furthermore if you need the REST API endpoint for the new resource, then it is present as the `Self` property of the `Links` property present in the model classes.

```
var createdPost = client.Posts.Create(post);
var restLink = createdPost.Links.Self;
```

**Comment by sabershariat20** [comment]
I also used this method. Posts are published in WordPress. But it does not return any value and enters the catch block

**Comment by navjot50** [comment]
Could you share your code snippet? If it goes in the catch block then it is throwing some exception. Could you share the stack trace of the exception?

**Comment by sabershariat20** [comment]
private static async Task CreatePost(WordpressPostViewModel model)
        {
           
            try
            {
                WordPressClient client = await GetClient(model.SiteUrl, model.SiteUsername,model.SitePassword);
                if (await client.IsValidJWToken())
                {
                    var post = new Post
                    {
                        Title = new Title(model.PostTitle),
                        Content = new Content(model.PostContent),
                        //Link=new string("123"),
                        Slug=new string(TextConvertors.fixUrl(model.PostTitle)+model.ReportajId)
                        
                    };
                  
                    var createdPost = await client.Posts.Create(post);
                    var PostLink = createdPost.link;
                }

                
            }
            catch 
            {
                
                //Console.WriteLine("Error:" + e.Message);
            }
        }

        private static async Task<WordPressClient> GetClient(string SiteUrl, string SiteUsername, string SitePassword)
        {
            if (!SiteUrl.StartsWith("https://") || !SiteUrl.StartsWith("http://"))
                SiteUrl = "https://" + SiteUrl;

            SiteUsername = EncodeAndDecodeString.Decrypt(SiteUsername);
            SitePassword = EncodeAndDecodeString.Decrypt(SitePassword);

            // JWT authentication
            var client = new WordPressClient(SiteUrl + "/wp-json/");
            client.AuthMethod = AuthMethod.JWT;
            await client.RequestJWToken(SiteUsername, SitePassword);
            return client;
        }

**Comment by sabershariat20** [comment]
The program runs properly up to this point and the content is published in WordPress :

var createdPost = await client.Posts.Create(post);

But after the content is published, it enters the catch block  
And waits for WordPress to send the error but WordPress does not return any value even exception .

**Comment by sabershariat20** [comment]
I also put the necessary values ​​in . htaccess

install Plugins wp-api and jwt and put this in wp-config :

define('JWT_AUTH_SECRET_KEY', 'sje...........');

define('JWT_AUTH_CORS_ENABLE', true);

**Comment by sabershariat20** [comment]
get() does not work either. I think wordPress actually recieve api and do the tasks ,  but does not return any answer and result

**Comment by navjot50** [comment]
Your catch block does not capture the exception. To capture the exception use:

```
catch(Exception e) {
    Console.WriteLine(e.Message)
}
```
Once you can print the exception’s stack trace, share it here. Although, at the moment it seems that there isn’t any issue with the library but maybe your configuration is not working properly.

**Comment by sabershariat20** [comment]
Yes, now I think the problem is with the file .httacsess and wp-config configuration. 

Can you send the correct .htaccess configuration guide and Compatible jwt and wp-rest plugins version?
============================
I use these plugins
Wp rest api v2.0(beta)
Jwt 1.2.6
Wordpress :  5.7.5
===========================
. httacsess :

RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
===================================
Wp-config :

define('JWT_AUTH_SECRET_KEY', 'MY-KEY');

**Comment by sabershariat20** [comment]
Yes, now I think the problem is with the file .httacsess and wp-config configuration

Can you send the correct .htaccess configuration guide and Compatible jwt and wp-rest plugins version?
I use these plugins:

Wp rest api v2.0(beta)
Jwt 1.2.6 
Wordpress :  5.7.5 
RewriteEngine on 
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

Wp-config : 

define('JWT_AUTH_SECRET_KEY', 'MY-KEY');

**Comment by navjot50** [comment]
You don’t need the Wp rest api v2.0 plugin. You can uninstall it. To configure the authentication read through https://en.wordpress-plugins-list.com/jwt-authentication-for-wp-rest-api-enrique-chavez/

**Comment by ThomasPe** [comment]
stale
