### ISSUE TITLE
Problems with create Media

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#30]
Hi there!
Now I will offend at WP REST API Media endpoint and json schema.
1) I can't understand why they use 2 diferents statuses for media GET(ALL)/POST and for Get with query builder.
Retrive all and Post requests available statuses are _publish, future, draft, pending, private_, but only in get filtered media available statuses are _inherit, private, trash_ (https://developer.wordpress.org/rest-api/reference/media/)
WTF? Why the do so and only for media (I dont find this piece of shit (sorry) in docs for other types, may be media is not alone)
But we can repair it easy with one Status enum for Get ALL and POST, and another status enum for query builder. I'll do that in my fork and it will be included in the next PR. But this is not the main problem
2) In our current implementation we cannot upload any media files (audio, image, video). We only can create empty media post with some parameters but without attachment.
To upload new Media with attachment we should create a new method with param like "pathToMediaFile", read this file to byte[] array and post it to WP REST API, but .NET Standard 1.1 doesn't support any api to work with files!!! This api included only in .NET Standard 1.3+. NET Standard 1.1 only can operate with Streams, but not include methods like File.ReadAllBytes.
So we should make a decision:
- Upgrade to .NET Standard 1.3 and manipulate with files in our library
- Or save .Net Standard 1.1 and force users of our library to convert the file into a stream by himself
I'll try variant 1 (upgrade to .Net standard 1.3) and it works

And some fun with content-disposition header (info about this not included in official docs)
https://wordpress.stackexchange.com/questions/209928/add-media-with-wp-rest-api-v2

**Comment by ThomasPe** [comment]
1. without having looked at the docs (yet), is it possible that the posts and media simply have different 
publish statuses? To be save we'll probably have to create an extra enum for each scenario, you're right.

2. Maybe another option could be to create an extension package to WordPressPCL that includes tools like this (WordPressPCL.Utility or similar). That one could depend on .NET Standard 1.3 without impacting the base package. You think that could be done in a way that makes sense?

**Comment by polushinmk** [comment]
1. We have to do just that, but I still do not understand why the WP REST API developers made different statuses for creating Media and for filtering through our query builder.
The question was more emotional, because I do not understand why they did different statuses, and only for Media
2. In my opinion, the library without the ability to upload the contents of the Media attachment will be an incomplete library. It seems to me that we should not only create an empty media type but also fully upload media files of all supported types (image, aduio, video, pdf etc)
The question is how we will do it:
1) will take the path to the file and convert it into an array byte []. For this we need to upgrade to .NET Standard 1.3
2) will receive Stream from clients, which will be converted to an byte [] array. For this we do not need to update, but then we shift the work of converting the file to stream to the user of the library

I think this is not good practice to implement the core feature in separate package, but may be we can realize variant 2 in current version that use .NET Standard 1.1 and create a package with realization of 1 variant with .Net standard 1.3

**Comment by ThomasPe** [comment]
Yes, it should certainly be possible to upload files in the core package! I meant we could implement it like you propose in 2.2.) and have a wrapper for working with file paths in a separate package. 

I'm not sure how much extra work it would be to have two versions of the same package with different dependencies - also I don't think that's something that nuget supports, right?

I guess eventually we're gonna drop support for .NET Standard 1.1 since Windows Phone will become less relevant quickly. But before switching to 1.3 maybe .NET Standard 2.0 will be the way to go - I have not fully looked into that yet.

**Comment by polushinmk** [comment]
Ok! I will work on variant 2.2.
Whats about create additional nuget package - may be we can cxreate a package only with one extension method for Media class, which will input file path. So it will not be a clone of the main package but will be an additional package.
Eventually I agree that you need to consider the option of switching to version 1.3 or even 2.0

**Comment by ThomasPe** [comment]
looks like you can actually publish a single nuget package for multiple targets. The current alpha is .netstandard1.1 and .netstandard2.0 compliant.

So we could add those additional features by just wrapping them in 
```csharp
#if NETSTANDARD2_0
// netstandard 2.0 code
#endif
```

https://docs.microsoft.com/en-us/dotnet/standard/frameworks

**Comment by polushinmk** [comment]
Docs updated
https://github.com/wp-net/WordPressPCL/wiki/Working-with-Media

**Comment by ThomasPe** [comment]
Awesome, thanks!
