### ISSUE TITLE
Add constructors for model classes with required values 

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#31]
I have a suggestion to add to model classes (Post, User,Media etc) constructors with required parameters. Required parameters - fields required to create entity in WP REST API
Example: in WP API for user creation required parameters are: username, email, password. Without this params we cannot create user.
I think that we should block opportunity to send non-complete create request to end users of  this library and might help them to understand which parameters are required for request.
But this change has the other side - it breaks DTO pricniple that DTO class must not have any logic in it (I think that simple constructor is an logic). But may be I am wrong and constructor with simple logic that pass input values to thier properties is not logic and not breaks the DTO pricnipe and we can do it simple

**Comment by ThomasPe** [comment]
I agree that having an additional constructor that takes all required input parameters does not break DTO principles. 
You should be able to create "empty" objects without any parameters in case you want to change them at a later point before actually sending the to the server. This way you still might run into issues with incomplete objects but that's a tradeoff I think we'll have to live with. A good documentation and IntelliSense comments to help with creating new objects should be enough I guess.

**Comment by polushinmk** [comment]
And so we should have 2 constructors: 1 empty constructor and 1 constructor with required fields. Did I understand you correctly?

**Comment by ThomasPe** [comment]
That's what I would propose, yes.
