### ISSUE TITLE
Specified cast is not valid exception.

### ISSUE THREAD

**Issue by nicomara** [wp-net/WordPressPCL#320]
Hi, why occur "invalid cast" exception here:
`   client = new WordPressClient(UriString);
            //fix casting exception
            var listOfNews = (IEnumerable<Post>)InitPosts();
            listOfPosts = new ObservableCollection<Post>(listOfNews);
        }`
`       public async Task<IEnumerable<Post>> InitPosts()
        {
            var posts = await client.Posts.GetAllAsync();
            return await Task.FromResult(posts);
        }`
What's wrong with post type? This code come from .Net MAUI app.
Thanks.

**Comment by ThomasPe** [comment]
this seems like not an issue with this library.
