### ISSUE TITLE
I Can't Create User, I'm doing it wrong? 

### ISSUE THREAD

**Issue by SirAbdllah** [wp-net/WordPressPCL#334]
I have not used the api before but I am trying to create a page to register an account in Wordpress, at first I made this code but it does not indicate an existing error and does not perform the task

This is a picture of the code

I used  .net WebForm 
![Capture](https://user-images.githubusercontent.com/119009127/203854570-7141b6a8-aca3-46ab-9526-e423e9714059.PNG)

**Comment by SirAbdllah** [comment]
WordPressPCL.Models.Exceptions.WPException: 'JWT is not configured properly.'

it show this after trying many times

**Comment by SirAbdllah** [comment]
WordPressPCL.Models.Exceptions.WPException: 'Authorization header malformed.' 
now it show me this

**Comment by ThomasPe** [comment]
The code you have looks fine, I assume it's still an issue with your JWT config. Are any other calls to the REST API working that require authentication? Creating posts?

**Comment by ThomasPe** [comment]
stale
