### ISSUE TITLE
Server returned HTTP status NotFound

### ISSUE THREAD

**Issue by ullfindsmit** [wp-net/WordPressPCL#342]
I am using wordpress on WIMP and I get a "Server returned HTTP status NotFound" when I try to authenticate.

```
Dim client = New WordPressClient("http://www.myserver.com/wp-json/")
Dim isValidToken = client.Auth.IsValidJWTokenAsync().Result
```

Error: WPUnexpectedException: Server returned HTTP status NotFound

**Comment by ThomasPe** [comment]
That means most likely that your JWT plugin was not correctly installed as the endpoint seems to be missing

**Comment by hbcondo** [comment]
```cli
System.AggregateException: One or more errors occurred. (Server returned HTTP status NotFound) ---> WordPressPCL.Models.Exceptions.WPUnexpectedException: Server returned HTTP status NotFound
```


FYI, I can replicate this error if the trailing slash of the URI is omitted:
```vb
Dim client = New WordPressClient("http://www.myserver.com/wp-json")
```

**Comment by ThomasPe** [comment]
stale
