### ISSUE TITLE
Update custom fields on post?

### ISSUE THREAD

**Issue by dburk2** [wp-net/WordPressPCL#344]
Is there a way to send an additional custom field value (other than Content, Excerpt, etc.) using the library via API? thanks

**Comment by simonhammes** [comment]
I just figured this out.

The following snippet seems to work:

```csharp
var post = new Post
{
    Id = 18,
    Meta = new Dictionary<string, string>
    {
        ["my-custom-key"] = "some value"
    },
};

await client.Posts.UpdateAsync(post);
```

Please note that all meta keys need to be registered using [`register_post_meta()`](https://developer.wordpress.org/reference/functions/register_post_meta/) _before_ you can use them, e.g.

```php
register_post_meta('post', 'my-custom-key', [
	'type' => 'string',
	'single' => true,
	'show_in_rest' => true,
]);
```

**Comment by ThomasPe** [comment]
this would be a good addition to the docs as well

**Comment by simonhammes** [comment]
> this would be a good addition to the docs as well

I will create a PR for that.
