### ISSUE TITLE
UserQueryBuilder Statuses

### ISSUE THREAD

**Issue by jeffkaffen** [wp-net/WordPressPCL#347]
Looking to add Statuses support to the CustomRequest.GetAsync, I think the below needs to be added in  UserQueryBuilder.cs

        //
        // Summary:
        //     Limit result set to posts assigned one or more statuses.
        //
        // Remarks:
        //     Default: publish
        [QueryText("status")]
        public List<Status> Statuses { get; set; }

**Comment by ThomasPe** [comment]
feel free to open a pr
