### ISSUE TITLE
Reintroduce .Get()-Methods with default values

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#36]
I think it would make sense to reintroduce the .Get-Methods to quickly get Posts, Pages etc. with default values. So await client.Posts.Get(bool embed) will simply return the 10 latest posts. For everything more sophisticated we already have our new QueryBuilder.

Thoughts?

**Comment by polushinmk** [comment]
I agree that it would make sense. We should create a list of common usefull methods, which we should realize.
My suggestion:

- Posts
- - GetPerPage(int perPage, int page=1)
- - GetAfterDate(DateTime after)
- - GetBeforeDate(DateTime before)
- Pages
- - GetByParent(int parentId)
- - GetPerPage(int perPage,int page=1)
- - GetAfterDate(DateTime after)
- - GetBeforeDate(DateTime before)
-Categories
- - GetByParent(int parentId)
- - GetPerPage(int perPage,int page=1)
- - GetBySearch(string search)
- - GetByPost(int postId)
- Tags
- - GetPerPage(int perPage,int page=1)
- - GetBySearch(string search)
- - GetByPost(int postId)
- Comments
- - GetByParent(int parentId)
- - GetByPost(int postId)
- - GetPerPage(int perPage,int page=1)
- - GetAfterDate(DateTime after)
- - GetBeforeDate(DateTime before)
- - GetBySearch(string search)
- Media
- - GetByParent(int parentId)
- - GetPerPage(int perPage,int page=1)
- - GetAfterDate(DateTime after)
- - GetBeforeDate(DateTime before)
- - GetBySearch(string search)
- - GetByAuthor(int authorId)
- - GetByMediaType(Enum mediaType)
- - GetByMimeType(string mimeType)
- Users
- - GetPerPage(int perPage,int page=1)
- - GetBySearch(string search)

**Comment by ThomasPe** [comment]
I think we don't need quite that many in the first step. I was thinking of really just .Get() what will return the default API response. Additionally I'd add these:

- Posts
    - GetPerPage(int perPage, int page=1)
- Pages
    - GetPerPage(int perPage,int page=1)
- Categories
    - GetPerPage(int perPage,int page=1)
    - GetByPost(int postId)
- Tags
    - GetPerPage(int perPage,int page=1)
    - GetByPost(int postId)
- Comments
    - GetByPost(int postId)
    - GetPerPage(int perPage,int page=1)
- Media
    - GetPerPage(int perPage,int page=1)
- Users
    - GetPerPage(int perPage,int page=1)
    - GetBySearch(string search)

**Comment by ThomasPe** [comment]
I'll stick to the basic Get()-methods for the time being, we can introduce the rest on a need basis
