### ISSUE TITLE
`Users` does not contain a definition for `GetCurrentUserAsync` 

### ISSUE THREAD

**Issue by hbcondo** [wp-net/WordPressPCL#360]
Hi, the method `Users.GetCurrentUserAsync` appears in the documentation but it doesn't appear to be part of [WordPressPCL.Client.Users](https://github.com/wp-net/WordPressPCL/blob/799c42b5b9d8b835e7b26f76686a99ec7736fc69/WordPressPCL/Client/Users.cs). Could this please be confirmed? Thanks.

https://github.com/wp-net/WordPressPCL/blob/799c42b5b9d8b835e7b26f76686a99ec7736fc69/docs/I%20version%202.x/entities/users.md?plain=1#L26

**Comment by richardaubin** [comment]
![image](https://github.com/wp-net/WordPressPCL/assets/37956997/2470e63e-0807-448d-a7c3-fd0eab8bc8a0)

Just named wrong.

**Comment by ThomasPe** [comment]
guess we missed that on the rename. happy to take a PR

**Comment by ThomasPe** [comment]
fixed
