### ISSUE TITLE
Post.CreateAsync throws Error

### ISSUE THREAD

**Issue by mshasib** [wp-net/WordPressPCL#364]
I am trying to create a Post and get the following error
`Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'WordPressPCL.Models.Post' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.'
`
Here is my code:
```csharp
WordPressClient client = new WordPressClient("http://wpsite.com/wp-json/wp/v2/", defaultPath: "");

// Authentication
client.Auth.UseBasicAuth("user", "password");

// Create the post
Post post = new Post
{
   Title = new Title("Title"),
   Content = new Content()
   {
       Raw = "test"
   }
};
var response = await client.Posts.CreateAsync(post);
```

**Comment by mshasib** [comment]
i'm using .NET 8.0

**Comment by ThomasPe** [comment]
Sounds like your server is returning an error instead of the expected result. Can you try to get that response?

**Comment by mshasib** [comment]
The response is returning a list of posts in an array and as the code is expecting just a post object, it's failing in the deserialization step. I'm running this on a wordpress site hosted on wordpress.org. Do you think that they changed the response on their api?

**Comment by mshasib** [comment]
I was able to find the source of the issue. I was passing in `http` instead of `https` in the URI
