### ISSUE TITLE
Implementation of Taxonomies, Post revisions, Post Types, Post Statuses | Version 1.1

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#37]
Hi there!
I just looked at the structure of 4 unrealized endpoints: Post revisions, Post types, Post statuses and Taxonomies. All of them do not have a full CRUD structure, but implement only Read operations (Post revision still implement Delete). Implement them using the interface ICRUDOperation does not work, since almost all methods will not be implemented.
I have 2 solutions:

1. Split ICRUDOperation into 4 components: 
- IReadOperation
- ICreateOperation
- IUpdateOperation
- IDeleteOperation

Attention: this will NOT cause a violation of backwards compatibility, so can be used in version 1.1
2. Implement without using interfaces

Suggestions?

**Comment by ThomasPe** [comment]
If the CRUD-Interface does not work I'd propose to simply remove the interface. Let's not make it more difficult than it needs to be.

Thinking about it more, same goes for the Media-Create-Method. Having a method that throws an exception just so we can fulfill an interface that does not fit our need (in this specific case) is probably not the best design. Usability of the nuget package is more important than applying all clean-code-principles.

So lets use the interface for those methods where it makes sense and remove them where it does not.
Do you agree?

**Comment by polushinmk** [comment]
You are right and I also dont like that Media endpoint throws an exception too.
But in my opinion interfaces is also a way to control ourself, that all endpoints realisation is the same anc contains all methods and also interfaces a way for developers to extend library functions - they can realize interface for their uses.
I would like the code to be strongly typed, re-used with a minimum of repetitions. Now we have a situation, that all client classes implement identical methods Create, Update, Delete, Get, GetAll and they differ only in the type of received and returned values. A lot of code that does the same thing in different places. If you suddenly have to change the implementation of one method, then you will have to change it in several places at once.
Create from Posts
```
public async Task<Post> Create(Post Entity)
        {
            var postBody = new StringContent(JsonConvert.SerializeObject(Entity).ToString(), Encoding.UTF8, "application/json");
            return (await _httpHelper.PostRequest<Post>($"{_defaultPath}{_methodPath}", postBody)).Item1;
        }
```
Create From Comment
```
public async Task<Comment> Create(Comment Entity)
        {
            var postBody = new StringContent(JsonConvert.SerializeObject(Entity).ToString(), Encoding.UTF8, "application/json");
            return (await _httpHelper.PostRequest<Comment>($"{_defaultPath}{_methodPath}", postBody)).Item1;
        }
```
This methods are identical.

I have an idea of ​​how this can be solved and probably I should offer it even before the release of 1.0:
Still, split ICRUDOperation into components. Create an abstract class CRUPOperation, which would implement all of these interfaces. Make client classes inherit this abstract class, instead of interfaces. Then the same type methods Create, Update, Delete, Get, Query would be defined in one place once. And in classes where it is not necessary - such as Post revision, Post Types and others, you could inherit only those interfaces that they really need.

I can realize it and this will not break compatible with current realization.

You are maintainer of this library and the last word is for you.

**Comment by ThomasPe** [comment]
I like this approach. If we can save code, I am all for it.
My priority is that it should be easiest for developers to use this library without any unexpected behaviours.
Other than that having Interfaces and abstract classes to keep the code clean is certainly a good thing!

**Comment by polushinmk** [comment]
I`ll do it all in  #38 PR but I need a review about Revisions UX for developers.

**Comment by ThomasPe** [comment]
Looking good for now, tests are running.
Let's try this in production :-)
