### ISSUE TITLE
Examples on the 'Quickstart' page are misleading due to HTTP usage.

### ISSUE THREAD

**Issue by papsl** [wp-net/WordPressPCL#371]
I suggest changing examples on Quickstart to use HTTPS schema, from:

```
var client = new WordPressClient("http://demo.wp-api.org/wp-json/");
```
to
```
var client = new WordPressClient("https://demo.wp-api.org/wp-json/");
```
Since WordPress authentication only works when TLS is used and in case of HTTP will return "Sorry, you are not allowed to create posts as this user".

**Comment by papsl** [comment]
I changed the readme.md file and created #372 pull request. Since I lost a few hours due to HTTP in example today. :)

**Comment by ThomasPe** [comment]
sorry for the late merge, much appreciated
