### ISSUE TITLE
Please update package in Nuget

### ISSUE THREAD

**Issue by mykeels** [wp-net/WordPressPCL#4]
Hello,

The package for this project on Nuget does not contain ListPostsBySearch ...

**Comment by ThomasPe** [comment]
you're right. I'm currently looking into automatically updating the nuget package from the master branch. I'll try to update the package this weekend manually.

**Comment by ThomasPe** [comment]
the nuget package has just been updated to the latest commit :-)

**Comment by mykeels** [comment]
Hello ... could you update the package again with the latest changes?

**Comment by ThomasPe** [comment]
done, should be available soon
