### ISSUE TITLE
CRUD - Create result error

### ISSUE THREAD

**Issue by mathieumack** [wp-net/WordPressPCL#44]
Hi,

When I use the Create method in order to create a category, the server returns a 201 http status code, but when the response is readed, the content starts with :
_< head >< title >Document Moved< /title >< / head>< body >< h1 >Object Moved< / h1 >This document may be found < a HREF="/wp-json/wp/v2/categories/1414">here< / a>< / body >{"id":1414,"count":0,"description":"Description category","link":"htt_

So the Deserialize (HttpHelper - Line 92) throws an error.

Has someone already get this issue ?

**Comment by mathieumack** [comment]
Ok it seems that there is a know issue when a WordPress instance is deployed on Microsoft Azure.
I close this thread.

**Comment by ThomasPe** [comment]
Yeah, this is really annoying
