### ISSUE TITLE
When creating nothing happens

### ISSUE THREAD

**Issue by rochapablo** [wp-net/WordPressPCL#46]
I'm getting token valid

```
var isValidToken = await client.IsValidJWToken();
```

But when I create something, I got nothing

```
var user = new User();
user.FirstName = "The Mail";
user.UserName = "themail";
user.Password = "123@abc";
user.Email = "themail@gmail.com";
client.Users.Create(user);
```

What am I missing?

**Comment by ThomasPe** [comment]
WordPress is a bit weird with what fields are required to create a User. Have you tried adding the nickname? 
This code works in the Tests:

    var user = await client.Users.Create(new User(username, email, password)
    {
        NickName = "nickname",
        Name = "name",
        FirstName = "firstname",
        LastName = "lastname"
    });

**Comment by rochapablo** [comment]
It worked! Thank you.
