### ISSUE TITLE
Users.GetAll not returning all users when auth set to true

### ISSUE THREAD

**Issue by VorTechS** [wp-net/WordPressPCL#47]
Firstly, let me start by stating that I'm not familiar with the WordPress API, or WordpressPCL.
Secondly thank for a potentially great starting point for interacting with WordPress!

I have an integration project I'm working on and started with the WordPressPCL nuget package in my project (a WinForms application), and then subsequently downloaded the git repo and managed to get the WordPressClient source running under Visual Studio 2015.

I had to do this because, the NuGet package when used with my WordPress installation (WordPress 4.8.1) seems to only be returning the admin users when calling Users.GetAll:

    var _wordPressUsers = (List<WordPressPCL.Models.User>) await _wordPressClient.Users.GetAll();

As a starting point, I modified the call to use authorization (as I realised that's going to make the difference), so changed the call to:

    var _wordPressUsers = (List<WordPressPCL.Models.User>) await _wordPressClient.Users.GetAll(false, true);

..and the situation became worse as now nothing was returned.  Checking through the source code at the point: 

    var responseString = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

...the response string contains the site home page HTML and not a JSON object as expected (although the response code was 200).

Following that, I thought I'd check to see if this was a problem with the Wordpress API by logging into Wordpress as the API user (using FireFox), and browsing to the API endpoint:

    MyWebsite.com/wp-json/wp/v2/users?per_page=100&page=1

...sure enough, I only get 4 users (out of 117, incidentally all of these 4 being the admin users).  Then I checked the request headers under FireFox and realized it was missing the authentication header, so modified the header using the token used by the WordPressClient:

    Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9iZW5jaG1hcmttaW5lcmFscy5jb20iLCJpYXQiOjE1MDUxMjY4MjQsIm5iZiI6MTUwNTEyNjgyNCwiZXhwIjoxNTA1NzMxNjI0LCJkYXRhIjp7InVzZXIiOnsiaWQiOiIxMTMifX19.431EpDbFoEBI8isfbSHFdkboHLqt3jxlY2BOwEzUUak

Low and behold, the first 100 users of 117 were returned.

Experimenting a bit more, I removed the Cookies header from the browser, and I then get the original behaviour when Authorization is enabled, as I'm re-directed to the Home Page (checking the network traffic this is preceeded by a 302 redirect).

Which doesn't sound right.  So I'm obviously doing something wrong.

Source I'm using:

                    _wordPressClient = new WordPressClient(_wpBaseUrl);
                    _wordPressClient.AuthMethod = AuthMethod.JWT;

                    await _wordPressClient.RequestJWToken(_wpUser, _wpAuth);
                    if (await _wordPressClient.IsValidJWToken()) {
                            var _wordPressUsers = (List<WordPressPCL.Models.User>) await _wordPressClient.Users.GetAll(false, true);

                    }

Should the client/API require a cookie collection in order for this to work?
Or have I missed something fundamental?

**Comment by polushinmk** [comment]
Hi!
I tested your last code on 2 different sites:
- default GetAll returns me only admin user
- GetAll(false,true) returns all users

So could you send your site url

**Comment by VorTechS** [comment]
I've done a little more digging.  I installed the Rest API Log plugin, and it seems the API _is_ responding with the correct data but between the call, and what's returned to the HTTPClient, there's a re-direct taking place.  

It seems there was an old(er) issue with the API requiring permalinks to be refreshed, but I'm not using plain links, but post name links.

So, there must be a problem with the ReWrite Rules somewhere.... :/

**Comment by polushinmk** [comment]
It really seems to be IIS problem and the responce from the server contains rubbish info like that:
`<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="http://benchmarkminerals.com/wp-login.php?loggedout=true">here</a></body>`
after it becomes valid JSON with all users list.
I see, that you use IIS hosting (maybe Azure?). It seems be like #44 error and this PR #45  may add some hook to fix this behaviour.
@ThomasPe I think, that we should accept PR #45 and release 1.1.1 version and update README with usefull example how to fix this behaviour on IIS server. Or may be add to HttpHelper class parameter useIIS, which will be clean server responce from all this rubbish.

**Comment by ThomasPe** [comment]
unfortunately after merging the milestone1.1 branch PR #45 has some merge conflicts, so those would need to be addressed first.
I agree that providing guidance on those IIS issues is a good idea since people using this package are more likely to run into this as it's all Microsoft-related.

**Comment by mathieumack** [comment]
I @VorTechS , if you need to use the lib, you can temporary download my fork : https://github.com/mathieumack/WordPressPCL

In order to remove the html pre generated code, you must configure the httpClient with this method :

`var client = new WordPressClient("uri");

            client.HttpResponsePreProcessing = (responseString) =>
            {
                var clearedString = responseString.Replace("\n", "");
                var regex = @"\<head(.+)body\>";
                return System.Text.RegularExpressions.Regex.Replace(clearedString, regex, "");
            };`

With it, the response will be processed and the html wode will be removed before calling the jsonconvert.DeserializeObject method.

**Comment by VorTechS** [comment]
Thanks.  I'll give it a go either later, or tomorrow.

**Comment by VorTechS** [comment]
What needs to be done on the server to enable the response to contain the JSON data that the API tries to send?  

The response I'm getting doesn't actually contain any JSON data, so the post-processor can't do anything.

**Comment by VorTechS** [comment]
Ah, okay, I see what needs to be done.  I'll pop a solution here with the relevant code for anyone else that needs it.  I'd merge the changes, but I've had to fudge the project a lot to get it working with my project (ie, no support for (var something, var somethingelse) style variable meaning I had to encapsulate the response messages as a 'LastReponse' type property:

Anyway, here's what I changed in the HTTP helper to sort out the re-direct issue:

   public class HttpHelper
    {
        private string _WordpressURI;
        private bool _successResponseCodeIsFound = false;

        /// <summary>
        /// JSON Web Token
        /// </summary>
        public string JWToken { get; set; }
        /// <summary>
        /// Constructor
        /// <paramref name="WordpressURI"/>
        /// </summary>
        /// <param name="WordpressURI">base WP RESR API endpoint EX. http://demo.com/wp-json/ </param>
        /// <param name="apiSuccessCodeIsResponseFound">IIS / Azure deployments may re-direct API responses after successfully returning the data.  Set this to ignore the re-directs.</param>
        public HttpHelper(string WordpressURI, bool apiSuccessCodeIsResponseFound)
        {
            _WordpressURI = WordpressURI;
            _successResponseCodeIsFound = apiSuccessCodeIsResponseFound;
        }

        internal async Task<TClass> GetRequest<TClass>(string route, bool embed, bool isAuthRequired = false) where TClass : class
        {
            string embedParam = "";
            if (embed)
            {
                if (route.Contains("?"))
                    embedParam = "&_embed";
                else
                    embedParam = "?_embed";
            }
            HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.ExpectationFailed);

            HttpClientHandler clientHandler = new HttpClientHandler
            {
                AllowAutoRedirect = false,
            };

            clientHandler.CookieContainer = _cookieContainer;

            using (var client = new HttpClient(clientHandler))
            {
                if (isAuthRequired)
                {
                    //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Utility.Authentication.Base64Encode($"{Username}:{Password}"));
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JWToken);
                }
                try
                {
                    response = await client.GetAsync($"{_WordpressURI}{route}{embedParam}").ConfigureAwait(false);
                    var responseString = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                    if (response.IsSuccessStatusCode || (response.StatusCode == HttpStatusCode.Found && _successResponseCodeIsFound))
                    {
                        return JsonConvert.DeserializeObject<TClass>(responseString);
                    }
                    else
                    {
                        Debug.WriteLine(responseString);
                    }
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("exception thrown: " + ex.Message);
                }
            }
            return default(TClass);
        }

Combine that with the post-processor, and you get the data you want!

Thanks for pointing me in the right direction guys!

**Comment by VorTechS** [comment]
It might be better, rather than coping with the 'Found' status code, accepting 'params HttpStatusCode[] successCodes', and storing these codes in a private variable then checking the locallly stored codes for presence of the returned code would be a better way to determine success.  That way, if IIS deployments behave differently by returning different status codes, it can easily be solved.

**Comment by ThomasPe** [comment]
Can this issue being resolved by using [HttpResponsePreProcessing](https://github.com/wp-net/WordPressPCL/wiki/HttpResponsePreProcessing)?
