### ISSUE TITLE
Add library to WP REST API docs

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#54]
Hi!
I think that library code is stable and ready for production use, so it is possible to add info about lib to official WP REST API Handbook.
https://developer.wordpress.org/rest-api/using-the-rest-api/client-libraries/
But I can`t find anyone from WP to write about this on this page.

**Comment by darklx** [comment]
Cool Library！

**Comment by ThomasPe** [comment]
My PR has finally been merged, so now we're listed on the docs :-)
https://developer.wordpress.org/rest-api/using-the-rest-api/client-libraries/
