### ISSUE TITLE
Add posts meta tag

### ISSUE THREAD

**Issue by rochapablo** [wp-net/WordPressPCL#55]
Is it possible submit a new meta tag in the moment that I'm creating the post?

Something like:

```
List<object> meta = new List<object>();
meta.Add(new KeyValuePair<string, string>("external_post_id", "9999"));
first.Meta = meta;
return await client.Posts.Update(first);
```

**Comment by ThomasPe** [comment]
Actually, I'm not sure. Have you tried it? Might as well work, the tool will serialize the whole post object and send it to the server.

**Comment by darklx** [comment]
I have tried.It's not work

**Comment by darklx** [comment]
+1

**Comment by rochapablo** [comment]
It doesn't work because It doesn't have the implementation.

I had to do by myself, where I
1. Create wp module that receive the post_meta
2. Create new class at C# project where post_meta is submitted

**Comment by darklx** [comment]
I implemented it, Here is the code:

Checkout the WordpressPCL source code , and add this field to Post.cs :
`
pubic class Post{
    public Dictionary<string, object> Metadata { get; set; }
}
`

add this code to your current theme functions.php or create an plugin:

`
add_action( 'rest_api_init', function(){
register_rest_field('post', 'metadata', array(
            'get_callback' => function ($post) {
                $id = $post->ID ? $post->ID : ($post->id ? $post->id : $post['id']);
                $r = get_post_meta($id, '', '');
                return $r ? $r : $id;
            },
            'update_callback' => function ($data, $post, $field_name) {
                $id = $post->ID ? $post->ID : ($post->id ? $post->id : $post['id']);
                if ($id) {
                    foreach ($data as $key => $value) {
                        if (!add_post_meta($id, $key, $value)) {
                            update_post_meta($id, $key, $value);
                        }
                    }
                }
                return true;
            },
        ));


        register_rest_field(
            'post',
            'content_raw',
            array(
                'get_callback' => function ($post, $field_name, $request) {
                    $id = $post->ID ? $post->ID : ($post->id ? $post->id : $post['id']);
                    // global $post;
                    $post = get_post($id);
                    // This is what we currently have...
                    //$output['rendered'] = apply_filters( 'the_content',  $post->post_content);
                    return $post->post_content;
                }
            )
        );
}) );
`
