### ISSUE TITLE
Logout method missing

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#56]
As far as I can tell there's currently no way log a user out (so forgetting the JWT token). We should add this.

**Comment by polushinmk** [comment]
I cannot find that endpoint in JWT plugin.
Only request token and validate
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by ThomasPe** [comment]
yeah, they would need an invalidate-token method.
But for now I think we could just have a public method removing the private token, right? This way no authenticated calls can be made anymore and the IsValidToken-Method should return false.
