### ISSUE TITLE
Response is always null after create request is made

### ISSUE THREAD

**Issue by vladop** [wp-net/WordPressPCL#59]
I successfully receive JWT token. I make good request, I see 201 created using wireshark. I can see that wordpress returns response, however this library gives me null for response: ( I tried creating posts and users)
var response=await client.Posts.Create (post)

**Comment by vladop** [comment]
I figured it out. My wordpress is on IIS, so I had to add
client.HttpResponsePreProcessing = (responseString) =>
{
    var clearedString = responseString.Replace("\n", "");
    var regex = @"\<head(.+)body\>";
    return System.Text.RegularExpressions.Regex.Replace(clearedString, regex, "");
};

However, when response is not successfull, HttpResponsePreProcessing  is not called,and response is null.

**Comment by ThomasPe** [comment]
Ah, that's a good catch. I'll look into what would be best to return - perhaps even an exception.

**Comment by vladop** [comment]
I think that wordpress returns some kind of error response with error details after unsuccessfull creation. Maybe it should return that, just like in case of success. HttpResponsePreProcessing is not called in case of error. In case of success it is called so I can strip unnecessary html from response (hosted on IIS) so deserializatiom works and response is not null anymore in case of success.

**Comment by polushinmk** [comment]
What will we do with it?
Throwing an exception which contains HTTP responce code, deserialized responce from WP (or may be raw, without deserializing)?
this will be one exception type, ex. HttpResponceException, or different kinds, like:
404 - NotFoundException (but it is IO exception)
401 - UnauthorizedAccessException (but is IO exception)
Or we create our custom exception types?

**Comment by ThomasPe** [comment]
You'll now see exceptions being thrown instead of returning null.
