### ISSUE TITLE
Delete requests get 405 method not allowed

### ISSUE THREAD

**Issue by vladop** [wp-net/WordPressPCL#63]
I am trying to delete posts. I get response: 405 method not allowed.
I tried configuring IIS with this:

      <system.webServer>
       <validation validateIntegratedModeConfiguration="false"/>
        <modules runAllManagedModulesForAllRequests="true">
           <remove name="WebDAVModule"/> 
        </modules>
    ... rest of settings here

I am not sure is there anything related to this library or to IIS configuration. Do you have IIS configuration that works. Obvoiosly tests passed, so it seems DELETE requests can work. POST and  GET requests are working correctly.

**Comment by vladop** [comment]
I solved by manually exucuting http request using Restsharp. I deleted post using POST method with X-HTTP-Method-Override header. This is just  another idea on how to make this library better. Maybe there should be at least option to execute  this alternative delete request like: client.Post.Delete(id,true,usingHttpMethodOverrideHeader:true) if you don't won't to change anything existing. Also I noticed JWT token is private propery, so I had to make another request manually to get this token. Maybe it should be exposed as public property. Just two ideas.

**Comment by ThomasPe** [comment]
Thanks for posting the solution you've found.
This Header would be necessary on all Delete-Methods, right? I don't really know much about the X-HTTP-Method-Override header and how common it is that this is required. I'm not against having this as an optional flag in the delete-methods / interface. I'll leave this open for now, maybe there are some additional thoughts from others here on this matter.

Regarding the JWT-Token, this is open for discussion in a separate issue #64
