### ISSUE TITLE
Menu Data

### ISSUE THREAD

**Issue by ourweb4** [wp-net/WordPressPCL#65]
In wordpress you can set up menus. Is there a way to get the menu data?

**Comment by ThomasPe** [comment]
No since this is not supported by the [WordPress REST API](https://developer.wordpress.org/rest-api/). You would have to write your own endpoint for this and then create a [custom request](https://github.com/wp-net/WordPressPCL/wiki/CustomRequests)

**Comment by ourweb4** [comment]
When you say endpoint I assume you mean an api function on the website. I know there is a couple of plug ins that will provide a menu api. However, I do not know if they will be in conflict.

**Comment by ThomasPe** [comment]
yes, this is something you'd have to provide on the server-side.
