### ISSUE TITLE
REsponse 0 when getting posts

### ISSUE THREAD

**Issue by hanniiel** [wp-net/WordPressPCL#66]
whenever i try to get all posts returns 0 i tried requests on ISS and Linux servers and response still 0, any idea ? 
-Xamarin Android
-VS 2017
and tried with https://github.com/z-ji/WordPressPCL/ and works fine but has issues wit ISS and HTTPS

**Comment by ThomasPe** [comment]
Do other methods work for you? Like a simple client.Posts.Get()?

**Comment by hanniiel** [comment]
Returns null :( with Get()

**Comment by hanniiel** [comment]
anyone had this issue ? still not working for me :( I'm sad ~

**Comment by ThomasPe** [comment]
Hopefully I can test it on Xamarin this week.
Have you tried to add the whole project to your solution instead of just the nuget package?

**Comment by tsjdev-apps** [comment]
I've tried it with Xamarin.Forms and everything is working. Maybe you've missed /wp-json at the initialization URL for the WordpressService?

**Comment by hanniiel** [comment]
working now =), thanks =), the problem was I was adding /wp/v2/ to the url. I'm babo~

**Comment by ThomasPe** [comment]
That's something we maybe should check in the PCL - and not add it when it's already present.

**Comment by hanniiel** [comment]
I understand, thank you very much It works great~
