### ISSUE TITLE
Multiple QuestionMark (?) appends in QueryBuilder

### ISSUE THREAD

**Issue by mykeels** [wp-net/WordPressPCL#7]
Hi, I just noticed that QueryBuilder appends QuestionMark (?) multiple times when multiple properties of the object are set. e.g.

```cs
(new QueryBuilder("demo.wp-api.org/wp-json/") {
 Page = 2,
 Embed = true
}).ToString(); 
```

the above code gives `http://demo.wp-api.org/wp-json/?page=2?_embed` instead of `http://demo.wp-api.org/wp-json/?page=2&_embed`

I'd send a pull request, but my last one hasn't been resolved yet. @ThomasPe

**Comment by ThomasPe** [comment]
Thanks, I'll try to test & merge your current pr tonight!

**Comment by ThomasPe** [comment]
Have you fixed this already? If so, feel free to add your pr ;-)

**Comment by mykeels** [comment]
Yes, I believe it came with my last pull request ... Sorry, I forgot to mention that ... I raised the issue after I had submitted the PR. 

I checked after it was merged and the issue had been fixed

**Comment by ThomasPe** [comment]
sounds good, thx
