### ISSUE TITLE
Not working with UWP when targeting Fall Creators Update

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#70]
When building a UWP App setting the Min version to Fall Creators Update 16299 the library will return null for all GetPosts-Calls (haven't tried others yet).

Setting Target version to Fall Creators update and Min Version to Creators Update 15603 works.

**Comment by polushinmk** [comment]
I dont know what is it, but in my notebook it freezes at return statement in PostRequest method from HttpHelper class.

**Comment by ThomasPe** [comment]
I'm getting a weird JSON.NET dll error - I guess there are some dependency issues there.

**Comment by ThomasPe** [comment]
Fixed for me with .netstandard2.0 - can you test the 1.3.0-alpha?

**Comment by polushinmk** [comment]
Yeah, works fine.

**Comment by ThomasPe** [comment]
Cool
