### ISSUE TITLE
I Can not Connect To My Rest Api Website

### ISSUE THREAD

**Issue by adelhoss** [wp-net/WordPressPCL#71]
hi thx for helpful Library 
I can not connect to rest api my web site
worpress version is : 4.8.2
and this link : http://marjafile.com/wp-json/ has exist 
i install jwt and enable header and added my token
when i use this code 
`            var client = new WordPressClient("http://marjafile.com/wp-json/");
            await client.RequestJWToken("admin", "passadmin");
            var posts = await client.Posts.GetAll();` 
always return 0 post and null

**Comment by ThomasPe** [comment]
hi,
did you block the public access to your /posts endpoint? 
If so you'll have to explicitly tell the client to use authentication when calling the API
`var posts = await client.Posts.GetAll(false, true);`
the first parameter "embed" will tell the method whether posts should include linked elements like featured images. The second one is the authentication flag (you'll want to use `true` here).

**Comment by polushinmk** [comment]
Yes http://marjafile.com/wp-json/wp/v2/posts/ return 403 Forbidden, so your site blocks posts endpoint.
But I find another issue - your date time culture format arabic with custom format (strings, not numbers).
date=۱۳۹۵-۱۲-۲۴ ۱۴:۵۶:۲۶ +۰۰:۰۰
our deserializer cannot deserialize that date correctly.
Could you tell me tour culture info from this https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo(vs.71).aspx
and your datetime format from WordPress Settings?
@ThomasPe I think we should add option to customize JsonDeserialization settings.

**Comment by ThomasPe** [comment]
Sure, we could certainly pass a settings object when creating the client.

**Comment by polushinmk** [comment]
@adelhoss Could you send me your culture info and datetime format from WP settings? It is necessary for debug
