### ISSUE TITLE
Pass deserialization settings into HttpHelper class.

### ISSUE THREAD

**Issue by polushinmk** [wp-net/WordPressPCL#72]
Due to #71 we should allow library users to cnahge default deserialization settings by passing it to HttpHelper class (like HttpPreProcessing).
It could be usefull if WP site uses non standard datetime format.
I will prepare PR later. Plz assign to me

**Comment by polushinmk** [comment]
I cannot reproduce #71 situation with strange datetime format. I try to change datetime format in my WP site, but it returns correct JSON date every time regardless of the format. I think, that problem is on server side.
But allows users to change serialization settings can be usefull in other cases.

**Comment by ThomasPe** [comment]
awesome - merged
