### ISSUE TITLE
Any sample for Newbie in C# and Xamarin Form?

### ISSUE THREAD

**Issue by kalipen** [wp-net/WordPressPCL#75]
Thanks for the Library , but Im very new at both C# and  Xamarin Form.
So any github working sample using this Library are very much appreciated.

Thanks!

**Comment by ThomasPe** [comment]
We're looking into creating a basic working Xamarin template similar to what we did for UWP with https://github.com/wp-net/WordPressUWP
cc @tsjdev-apps

**Comment by abresnev** [comment]
Thank you so much!

**Comment by kalipen** [comment]
Much appreciated!

**Comment by tsjdev-apps** [comment]
Hello @kalipen,
I've pushed today a first and very simple version of the Xamarin.Forms template. You can find it here: [https://github.com/wp-net/WordPressXF](https://github.com/wp-net/WordPressXF). New features will be added in the future.
