### ISSUE TITLE
Response null using context=edit

### ISSUE THREAD

**Issue by ManyouRisms** [wp-net/WordPressPCL#79]
I've been having mixed success getting responses from my local WordPress installation.

I do some processing on posts as they when they come in and require the use of the edit context. However when I add query.Context = Context.Edit, the response is NULL when it returns from Posts.Query(query).
The relevant lines are:
```
            Dim query = New Utility.PostsQueryBuilder
            query.Page = page
            query.After = time
            query.PerPage = _webConfigHelper.Get("jsonPostsPerPage")
            query.OrderBy = PostsOrderBy.Modified
            query.Order = Order.ASC
            query.Embed = True
            query.Context = Context.Edit

            _wordpressClient.AuthMethod = AuthMethod.JWT
            Await _wordpressClient.RequestJWToken(_user, _pass)
            Dim validToken = Await _wordpressClient.IsValidJWToken()

            If validToken Then
                Dim response = Await _wordpressClient.Posts.Query(query)
                Dim url = query.BuildQueryURL() ' just used to debug
                If response IsNot Nothing AndAlso response.Count > 0 Then
                    Dim rawposts = response.Select(Function(x) ConvertPost(x)).ToList()
                    Return rawposts
                End If
            End If
```

The JWT auth seems to be working as I can examine the token and it is the same one I can use in Postman to get results to the same URL. If i leave out setting the context to edit, I get a response that is not NULL.

Is this a bug, or am I doing something wrong?

**Comment by polushinmk** [comment]
Hi!
By default all query executed without auth headers.
You should explicitly use auth headers.
To do that changed Query method like this:
```vbnet
Dim response = Await _wordpressClient.Posts.Query(query,true)
```

**Comment by ManyouRisms** [comment]
Thank you i'm going to try that now. If that's the case then, should I update the README where it says

// check if authentication has been successful
var isValidToken = await client.IsValidJWToken();

```
// now you can send requests that require authentication
var response = client.Posts.Delete(postid); <-- should this be client.Posts.Delete(postid, true); or is it just GET by default that doesn't include the auth header?

``
