### ISSUE TITLE
Add support for ACF - "Advanced Custom Fields"

### ISSUE THREAD

**Issue by papsl** [wp-net/WordPressPCL#8]
I'm using ACFs (Advanced Custom Fields), they are returned as node "acf" when the appropriate plugin (https://github.com/airesvsg/acf-to-rest-api/) is enabled, example:
```json
...,    
"acf": {
      "projectyear": "2017",
      "projectowner": "wp-net"
    },
```
When creating new post they need to be send as "fields" node, example:
```json
..., 
    "fields": {
      "projectowner": "wp-net"
    },
```
Code can be found under pull requst https://github.com/wp-net/WordPressPCL/pull/9.

**Comment by ThomasPe** [comment]
Sorry that I've not been able to look at it yet. I'll do so asap!

**Comment by ThomasPe** [comment]
I think it would make more sense to put these kind of API additions inside additional packages, maybe like WordPressPCL.ACF so we don't clutter the core with code that's only useful for specific plugins. By inheriting the core classes everyone could just extend the client with the fields they need. I'll have to think about what a good structure could look like.
Does that make sense?

**Comment by papsl** [comment]
Sure! I like the idea of additional packages even more, it brings a lot of extensibility options. 
Also, it might be that ACF implementations are different from one WP plugin to another, in this case, we would break compatibility if it would be implemented one in core client.
Ok, let's give it a second thought.

**Comment by ThomasPe** [comment]
We'll discuss this further in the linked issue :-)
