### ISSUE TITLE
IsValidJWToken is false

### ISSUE THREAD

**Issue by sonnd9x** [wp-net/WordPressPCL#81]
I', trying to use this lib. But, I get probem

`client = new WordPressClient("http://duhoc.thaison.top/wp-json")
            {
                AuthMethod = AuthMethod.JWT
            };
            await client.RequestJWToken("username", "password");
            var IsValidToken = await client.IsValidJWToken();`
IsValidToken always return false.

**Comment by polushinmk** [comment]
Hi!
Are you sure, that you install this plugin
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
and configure it correctly?

> PHP HTTP AUTHORIZATION HEADER ENABLE
> 
> Most of the shared hosting has disabled the HTTP Authorization Header by default.
> 
> To enable this option you’ll need to edit your .htaccess file adding the follow
> 
> RewriteEngine on
> RewriteCond %{HTTP:Authorization} ^(.*)
> RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
> WPENGINE
> 
> To enable this option you’ll need to edit your .htaccess file adding the follow
> 
> See https://github.com/Tmeister/wp-api-jwt-auth/issues/1
> 
> SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
> CONFIGURATION
> 
> CONFIGURATE THE SECRET KEY
> 
> The JWT needs a secret key to sign the token this secret key must be unique and never revealed.
> 
> To add the secret key edit your wp-config.php file and add a new constant called JWT_AUTH_SECRET_KEY
> 
> define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');
> You can use a string from here https://api.wordpress.org/secret-key/1.1/salt/

**Comment by sonnd9x** [comment]
Thank you. It worked.
