### ISSUE TITLE
Can not connect to wp-json when deploy web app on Plesk hosting, Azure....

### ISSUE THREAD

**Issue by sonnd9x** [wp-net/WordPressPCL#83]
I make a web application using WordpressPCL, It's working on my localhost (VS debug). But, When I upload to hosting (plesk panel, Azure), All functions need authorized not working

`await client.RequestJWToken(user, pass);`
`await client.Posts.Create(_post);`

I checked with Fiddler, I don't see it call to /wp-json/

**Comment by ThomasPe** [comment]
what response do you get on your sever? can you add logging for each step? have you updated to the latest package?

**Comment by sonnd9x** [comment]
I used nuget version 1.3.0. This is response from server. When I tried call create post function.

> POST http://**************************/Post/Post HTTP/1.1
Host: wp1102.azurewebsites.net
Connection: keep-alive
Content-Length: 30
Cache-Control: max-age=0
Origin: http://********************
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://*********************/Post/View/1
Accept-Encoding: gzip, deflate
Accept-Language: vi,en-US;q=0.9,en;q=0.8
Cookie: CKFinder_Path=Files%3A%2F%3A1; ARRAffinity=10d43e97df985150b21ea8c6936bd05e2e9e2526de0574aa3727e6c61649735b; ASP.NET_SessionId=jqop5dyqsdo2j1xhu1xjv44v

postID=1&website=2&category=23
HTTP/1.1 302 Found
Cache-Control: private, s-maxage=0
Content-Length: 129
Content-Type: text/html; charset=utf-8
Location: /Post/View/1
Server: Microsoft-IIS/8.0
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 23 Nov 2017 13:06:30 GMT

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/Post/View/1">here</a>.</h2>
</body></html>

It not connect normally to wp-json
![issue](https://user-images.githubusercontent.com/9068745/33376917-1f9276cc-d542-11e7-9ad9-f72ab138b9eb.png)

**Comment by sonnd9x** [comment]
@ThomasPe Please help check this

**Comment by ThomasPe** [comment]
well, this isn't the request that is being made from ASP.NET to WordPress, right? can you remote debug your site on Azure?

**Comment by polushinmk** [comment]
What kind of .NET core version do you use?
If you use 2.0 please try this version of library (you must remove nuget package from solution and add dll from zip [WordPressPCL.zip](https://github.com/wp-net/WordPressPCL/files/1526727/WordPressPCL.zip) ).
It contains responce logger, it writes all responses to text file.
You must add one line, after initialization:
client.LogFilePath="path/to/logfile.txt";
excample
```c#
var client = new WordPressClient("http://site/wp-json/");
client.LogFilePath="path/to/logfile.txt";
await client.RequestJWTToken(user,password);
...
```

**Comment by sonnd9x** [comment]
Thank you I found my error, Thank for your support !
