### ISSUE TITLE
Comments failed to retrieve data when QueryBuilder.Comments.Statuses filter is defined

### ISSUE THREAD

**Issue by vmendivil** [wp-net/WordPressPCL#86]
Hi guys,

I'm developing on F# but I have also tested my scenarios using the test scripts you have in your repo, both my code and your test cases produce the same results, this way I make sure my code is working as it should based on your test scripts.

My issue is when using the Comments QueryBuilder to fetch comments by Status. This property seems not to be working, it doesn't matter what value I use, Approve/Spam/Pending, result is always null.

1) When building a QueryBuilder for Comments and passing any status, result is always null. Same happens in your test scripts.

Your test script with Statuses added:

    `[TestMethod]
        public async Task Comments_Query()
        {
            var client = await ClientHelper.GetAuthenticatedWordPressClient();
            var queryBuilder = new CommentsQueryBuilder()
            {
                Statuses = new CommentStatus[] { CommentStatus.Pending },
                Page = 1,
                PerPage = 15,
                OrderBy = CommentsOrderBy.Id,
                Order = Order.DESC
            };
            var queryresult = await client.Comments.Query(queryBuilder);
            Assert.AreEqual(queryBuilder.BuildQueryURL(), "?page=1&per_page=15&orderby=id&order=desc");
            Assert.IsNotNull(queryresult);
            Assert.AreNotSame(queryresult.Count(), 0);
        }`

My code:

    `member this.getProductComments () =
        async {
            let! client = this.getWordPressAuthenticatedConnection()
            
            let query = CommentsQueryBuilder()
            //query.AuthorEmail <- ""
            query.Statuses <- [|CommentStatus.Pending|]
            
            let queryString = query.BuildQueryURL()

            let! comments = client.Comments.Query(query, true) |> Async.AwaitTask
            //let! comments = client.Comments.GetAll() |> Async.AwaitTask // This works for all approved
            return comments
        }`

2) Since I'm not able to retrieve Pending (I assume is the same as unapproved) comments or Spam comments, what values should I change, just for testing, in my WordPress database to make at least one record match the criteria to be found when using a QueryBuilder with Status == Pending or Spam

For Spam comments I use Akismet, and for Pending comments I tried importing some comments in Draft status and approving already approved comments (existing comments and also comments created through your test scripts).

Thanks!

Victor

**Comment by polushinmk** [comment]
Hi! 
Thank you for your issue. 
I fix problem in #87 pull request.

**Comment by vmendivil** [comment]
Hi!
Thanks for the fix mate, will try to reproduce the fix and the issue later today!

**Comment by ThomasPe** [comment]
Did not mean to close the issue yet - but the fix has been released to nuget. :-)
Let me know if this fixes your issues.

**Comment by vmendivil** [comment]
Hi Thomas,

I get the latest nuget version and testing went as follows:

The code I used for testing is as follows:

    `       let query = CommentsQueryBuilder()
            query.Page <- 1
            query.PerPage <- 100
            query.Order <- Order.DESC
            query.OrderBy <- CommentsOrderBy.Id
            query.Statuses <- [|CommentStatus.Pending|]

            let! comments = client.Comments.Query(query, true) |> Async.AwaitTask`

Working:
* Pagination with a max of 100 records by page
* Pending status
* Spam status
* Trash status

NOT Working:
* Approve status -> returns always 0. If you use Comments.GetAll() it successfully retrieves all approved comments.

For what I need to do I can work with this fix since now I'm able to get Pending comments and do some extra data processing once I GetAll() the comments, but will be nice if it can be fixed.

I really appreciate the very quick response from you guys involved in this project, is really helpful.

Cheers!

**Comment by ThomasPe** [comment]
Have you tried setting the authentication flag to true? I think you can only get this field as an admin...

**Comment by ThomasPe** [comment]
Seems like this is another one of the really annoying inconsistencies in the WordPress API. Comments have a status of "approved", which is what the Enum of Status.Approved will be translated to. But to filter the Query the status needs to be set like this "status=approve" without the trailing 'd'.

Since approve is the default status you would just need to not set the query.Statuses at all to just get the approved ones. Does that help you?

We should look into removing the status silently from the QueryBuilder if it's set to Statuses.Approved, but I'm not quite sure how to do this best atm.

**Comment by vmendivil** [comment]
You are right, I just removed it and it fetches the right data. 

I don't know how to silently modify the QueryBuilder. Once I finish my code I will play a  bit with it and if by any chance I find a work around will let you know.

Thanks for your support!!!! :)
