### ISSUE TITLE
Changing status of a Comment from Pending to Approved not working

### ISSUE THREAD

**Issue by vmendivil** [wp-net/WordPressPCL#88]
Hi,

Not sure if this issue is related to WordPressPCL or to the WordPress API that won't allow to approve a comment from your library.

I'm running the following code:

`comment.Status <- CommentStatus.Approve; x.UpdateComment(comment)`

If I do the same but changing some other properties as the content of the comment or the author or some other properties, it just works fine.

Do you know if approving a comment can be done this way or if it's even possible through WordPressPCL library?

Thanks,

Victor

**Comment by polushinmk** [comment]
Hi!
Sorry, my mistake. Some time ago, I did not add the serialization attribute for the comment model (in our model it names Status, but in Json it must be named status). For Get and Create, this was not critical, but for Update it was critical.
Fixed in #89 PR

**Comment by ThomasPe** [comment]
Fixed in V1.3.3, available soon through nuget
thanks @polushinmk

**Comment by vmendivil** [comment]
Awesome, I will look for the nuget update later today if available and test it.

Thanks man!
