### ISSUE TITLE
Reuse HttpClient?

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressPCL#92]
We should consider reusing the HttpClient for all calls and not dispose it after each request.
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by polushinmk** [comment]
Good suggestion!
Please, create new dev branch

**Comment by ThomasPe** [comment]
I've created a features/static-httpclient branch that I'd like to merge back into milestone1.4 when done.
