### ISSUE TITLE
QueryBuilder Order Bug

### ISSUE THREAD

**Issue by sombe** [wp-net/WordPressPCL#93]
I noticed that in Wordpress API documentation the default order for posts is "desc"
(https://developer.wordpress.org/rest-api/reference/posts/#example-request)
but in the QueryBuilder class uses Order enum that have at first position "ASC" value.
In QueryBuilder.BuildQueryURL method at this point
`if (property.PropertyType.GetTypeInfo().IsEnum && (int)property.GetValue(this) == 0) continue;`
(int)property.GetValue(this) is 0 and in this way the parameter is not included.

My suggest is to reverse the order of enum like this:

```
    /// <summary>
    /// Order By direction
    /// </summary>
    public enum Order
    {
        /// <summary>
        /// Descending direction
        /// </summary>
        [EnumMember(Value = "desc")]
        DESC,

        /// <summary>
        /// Ascending direction
        /// </summary>
        [EnumMember(Value = "asc")]
        ASC
    }
```

This works fine for me.

**Comment by ThomasPe** [comment]
Good catch! PR? :-)
