### ISSUE TITLE
Please do not just hidden all the incorrect/unexpected http responses to 'Debug.WriteLine',just throw it!

### ISSUE THREAD

**Issue by 3Shain** [wp-net/WordPressPCL#96]
It's such a normal case to throw a Exception when getting unexpected result from any invoking, HTTP requests included. Otherwise,we can not catch the trouble exactly, but most users are unwilling to see just the alert 'xxxxx error/failed'. What's more the 'Task' does support throw exceptions during a task is running,while we can catch it where we start the task. I don't know why you didn't throw these troubles to us invokers . If you think a 'strong code' should throw no /a little exceptions ,that is totally wrong! All exceptions should be handled at correct place,not be hidden at the source.

**Comment by 3Shain** [comment]
anyway what I need is known WHY THIS REQUEST IS NOT SUCCESSFUL , but not just get a null value

**Comment by ThomasPe** [comment]
Actually, that is a very helpful comment. This is my first OS project people are actually using so I'm still learning. ;-)
Maybe you'd like to submit a PR showing how you would handle these exceptions?

**Comment by 3Shain** [comment]
I have made a sample showing how it works.
And from where I invoke the APIs like WordPressClient.Comments.Create without necessary authorization a WPException will be caught,with some information provided by server.
As to other Exception like JsonException ,etc, I boxed it in a new Exception instance and invokers can handle it in InnerException or just ignore it.
I only modified the GetRequest function ,and you can modify PostRequest/DeleteRequest function in the same way,or make the Exception handling more detailed. And finally I think it is necessary to leave some comments on public APIs (to show what type of Exceptions might be thrown when invoking it)

**Comment by ThomasPe** [comment]
I've just updated the nuget package with they exception changes - can you test it and give some feedback if that's how you expect the library to behave?
