### ISSUE TITLE
posts.Create always returns null in C# .NET 4.7 

### ISSUE THREAD

**Issue by hiromi3** [wp-net/WordPressPCL#98]
Hello,
I am using VS2017 C# with .NET 4.7 .
I could successfully build the following projects in this emvironment.
     WordPressPCL
     WordPressPCLTests
Then, I could successfully execute following commands from my Console application.
            var posts = await client.Posts.GetAll();
            var queryresult = await client.Posts.Query(queryBuilder);
and I could get the posts data.
But, when I execute the posts.Create, the return value was always null;
            var createdPost = await client.Posts.Create(post);
I can post to my WP site by using microsoft Word.
So, posting from the external application works fine.
If you can guess what causes post.Create problem, please let me know.

**Comment by aaldrich** [comment]
@hiromi3 I'm having this issue as well, did you ever figure out a solution?

**Comment by hiromi3** [comment]
Hi,
No, I could not solve the problem.
So, I gave up using WordPressPCL and I am using WordPressSharp.

**Comment by ThomasPe** [comment]
With the next update there should be better exceptions that might help figure out what's going on.

**Comment by ThomasPe** [comment]
I've just updated the nuget package to V1.4, maybe you'll now see the exceptions.

**Comment by ThomasPe** [comment]
Also, can you maybe share a repo?
